### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by gszesiek** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#10]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?return=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#4

**In which task and step of the codelab can this issue be found?**
Implement floorArea() for RoundTower 
8
Note: For the area values, it would be a nicer user experience to only show a couple of decimal places. This is out of scope for this codelab, but you could print the floor area using this: println("%.2f".format(floorArea))
**Describe the problem**
println("%.2f".format(floorArea)) -> println("Floor area: %.2f".format(floorArea()))

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@gszesiek 
Thank you so much for reporting this issue. This issue is fixed and will be published soon..
