### ISSUE TITLE
Android Basics: xml-layouts

### ISSUE THREAD

**Issue by bertucci25** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#100]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-xml-layouts#4

**In which task and step of the codelab can this issue be found?**
At the end of the section 5

**Describe the problem**
android:padding="16dp" is missing in the constraintLayout tag 

**Steps to reproduce?**

**Versions**
Chrome Browser

**Additional information**

![image](https://user-images.githubusercontent.com/81843234/113467533-e6128a00-9419-11eb-95de-b2798221063d.png)

**Comment by osuleymanova** [comment]
@bertucci25 
Thank you for reaching out to us. The issue is fixed and published.
