### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by patelsiddh** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#102]
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#2

In the code lab of "Calculate Tip" -> 3. View binding - at the end of the page in "Note" section, naming convention which is used to define binding class name mentions wrong detail.

Currently it is saying this: 
"The name of the binding class is generated by converting the name of the XML file _**to camel case**_ and adding the word "Binding" to the end." 
The screenshot:
![view_binding_naming_wrong](https://user-images.githubusercontent.com/66568312/113523256-b1ffac00-9574-11eb-8b15-3310104d9d5f.PNG)

**Steps to reproduce?**
1. Go to Android Basics in Kotlin course [Homepage](https://developer.android.com/courses/android-basics-kotlin/course)
2. Click on "Explore" of Unit 2: Layouts
3. Open the first chapter.
4. Click on "TAKE CODELAB" of 5th chapter [Name: Calculate the Tip].
5.  Click on [3. View Binding](https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#2) topic from left panel
6. Scroll down till the end of the page. 
7. Observe **Note:** and see error in statement as mentioned in above screenshot.

In step 7, instead of "to camel case", it should be "to pascal case".

**Comment by osuleymanova** [comment]
@patelsiddh 
Thank you for reaching out to us. The issue is fixed and published:

https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#2
