### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by Esh527** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#105]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance#7

**In which task and step of the codelab can this issue be found?**
Classes and inheritance in Kotlin

I am Unable to Find the NEXT Button. Please Help me out.

**Describe the problem**
![next button](https://user-images.githubusercontent.com/36148578/113713401-f0c46c00-9704-11eb-8795-418118f45f43.JPG)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@Esh527 
The issue that you presented to us is extremely important, and I thank you for bringing it to our attention. Actions will soon be taken to fix it.
