### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by Elvehi** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#106]
In "Modify classes in the hierarchy" section, in "Implement floorArea() for RoundHut" part, there is an error in the code under the third step. The constructor of RoundHut class contains "val residents: Int" instead of "residents: Int". In fact, RoundHut class is a subclass of Dwelling class.

**Comment by osuleymanova** [comment]
@Elvehi 
Thank you for reaching out to us. The issue is fixed and will be published soon:
open class RoundHut(
       residents: Int, val radius: Double) : Dwelling(residents) {
