### ISSUE TITLE
Android Basics: xml-layouts

### ISSUE THREAD

**Issue by Pshock13** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#108]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-xml-layouts#5

**In which task and step of the codelab can this issue be found?**
"Add a Switch for rounding up the tip"

**Describe the problem**
codelab states that 
"As noted earlier, you can't set match_parent on UI elements in a ConstraintLayout"

I'm running Android Studio 4.1.3 and it seems that setting 
```
layout_width="match_parent"
```
gives the same result as
```
layout_width="0dp"
layout_constraintStart_toStartOf="parent"
layout_constraintEnd_toEndOf="parent"`
```

The switch moves to the far right side of the screen and the view takes up the entire width of the screen no matter which of the two ways you code it.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 4.1.3
_API version of the emulator:_ 29

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@Pshock13 
Thank you for reaching out to us. The instructions in the codelab were updated. Please let us know if you still face any issues after all.
Happy coding!
