### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by kerphloo** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#11]
**URL of codelab**

[URL](https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator#3)

**In which task and step of the codelab can this issue be found?**

The problem is in the "Calculate the tip" task, step 4.

**Describe the problem**

This line:
```kt
binding.tipResult.text = getString(R.string.tip_amount, formattedTip)
```
doesn't work. This just sets `binding.tipResult.text` to simply "Tip Amount", and does not include `formattedTip`.

**Steps to reproduce?**
N/A? Or just follow the codelab.

**Versions**
_Android Studio version:_ 4.0.1
_API version of the emulator:_  23

**Additional information**
I am a beginner in Kotlin and Android Studio but I think I've solved it.
`getString()` is supposed to convert an integer to string (I'm not really sure how, all I know is that `R.string.tip_amount` is an integer) but the codelab is trying to feed an integer _and_ a string into it. 

I've got it to work properly using this:
```kt
binding.tipResult.text = "${getString(R.string.tip_amount)} $formattedTip"
```

If you're curious, this is my `strings.xml`:
```xml
<resources>
    <string name="app_name">tip calculator</string>
    <string name="round_up_tip">Round up tip?</string>
    <string name="ok_15">OK (15%)</string>
    <string name="good_18">Good (18%)</string>
    <string name="amazing_20">Amazing (20%)</string>
    <string name="how_was_the_service">How was the service?</string>
    <string name="cost_of_service">Cost of Service</string>
    <string name="calculate">Calculate</string>
    <string name="tip_amount">Tip Amount</string>
</resources>
```

**Comment by jtavva** [comment]
@kerphloo 
Thank you for reaching out to us.
In the task **4 Calculate Tip** -> **Display the tip**
You are supposed to update your `strings.xml`. I don't see your file is updated. 

> `<string name="tip_amount">Tip Amount: %s</string>`

If you update your file, the following code given in the  in the codelab should work as expected.

> `val formattedTip = NumberFormat.getCurrencyInstance().format(tip)`
>  `binding.tipResult.text = getString(R.string.tip_amount, formattedTip)`
