### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by RoloErre** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#111]
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#6
**In which task and step of the codelab can this issue be found?**

It seems that the binding code line is incorrect: The id for the XML layout is cost_of_service_edit_text (it could be found on the same Calculate tip pathway) and the Binding section of the codelab writes the binding using: binding.costOfService.text. I think it has to be: binding.costOfServiceEditText.text. I had to edit it like that for my code run properly.

Thanks!

**Comment by jtavva** [comment]
@RoloErre 
Thank you so much for reporting this issue. This is fixed and will be published soon.
Here is the updated code: 

```
fun calculateTip() {
    val stringInTextField = binding.costOfServiceEditText.text.toString()
    val cost = stringInTextField.toDouble()
    val selectedId = binding.tipOptions.checkedRadioButtonId
    val tipPercentage = when (selectedId) {
        R.id.option_twenty_percent -> 0.20
        R.id.option_eighteen_percent -> 0.18
        else -> 0.15
    }
    var tip = tipPercentage * cost
    val roundUp = binding.roundUpSwitch.isChecked
    if (roundUp) {
        tip = kotlin.math.ceil(tip)
    }
    val formattedTip = NumberFormat.getCurrencyInstance().format(tip)
    bin
```ding.tipResult.text = getString(R.string.tip_amount, formattedTip)
}
