### ISSUE TITLE
Android Basics: xml-layouts - padding missing in final code

### ISSUE THREAD

**Issue by PashkoVasa** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#112]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-xml-layouts#3

**In which task and step of the codelab can this issue be found?**
Task 4: Build the layout in XML

**Describe the problem**
`android:padding="16dp"` is missing
In the beginning it is implemented but in the final code on the bottom of the page,  (where it says "At this point, your XML should look like this.") `android:padding="16dp"` is missing. 

**Steps to reproduce?**
1. Go to... Step 4 Build the layout in XML
2. Go to... the Bottom of the page. 
3. See error... android:padding="16dp" 

**Versions**

**Additional information**

**Comment by jtavva** [comment]
@PashkoVasa 
Thank you so much for reporting this issue. This is fixed and will be published soon.

Updated code for your reference. 
```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:padding="16dp"
    tools:context=".MainActivity">
...
```
