### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by anas4u02** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#113]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#4

**In which task and step of the codelab can this issue be found?**
Step 5: Modify classes in the heirarchy

**Describe the problem**
The carpet area for round Tower will be Carpet area of Round Hut * floors of round Tower.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/43414023/114295044-42337900-9ac0-11eb-842e-98d5091de03d.png)

**Comment by jtavva** [comment]
@anas4u02 

This section has been updated in the codelab to calculate the length of the carpet required for a single floor:

```
fun calculateMaxCarpetLength(): Double {
    
    return sqrt(2.0) * radius
}

```

Thank you so much for reporting this issue. This is fixed and will be published soon.
