### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by Productivix** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#117]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#2

**In which task and step of the codelab can this issue be found?**
5 (last)

**Describe the problem**

the "binding" word is underlined : there is a suggestion : see capture 
![Capture](https://user-images.githubusercontent.com/6737060/114667377-b445d100-9cff-11eb-93af-46d1ead83350.PNG)

**Steps to reproduce?**
1. just follow the training

**Versions**
_Android Studio version:_ 4.1.3 of March11
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@Productivix 
Could you please re-build the project and do a gradle sync and check if the error persists. 
Also please compare your code with the solution code.

**Comment by Productivix** [comment]
hi, I reopen the project with upgrade Android Studio Plugin version 4.1.3 to version 4.2.1:
Upgrade Gradle version to 6.7.1.
Upgrade AGP dependency from 4.1.3 to 4.2.1.

and the problem is solved - thanks
