### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by Productivix** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#119]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator&authuser=1#5

**In which task and step of the codelab can this issue be found?**
inspect the code

**Describe the problem**
the file option of which you are speaking about not exists any more
![Capture](https://user-images.githubusercontent.com/6737060/114679489-7b602900-9d0c-11eb-89af-fb9aa4367908.PNG)

**Steps to reproduce?**
1. Go to...Analyse >inspect Code
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 4.1.3 march 11
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by Productivix** [comment]
in fact the first time you activate Analyse >inspect Code, you get my screen shot without file option, 
and the second time , you get your version with file option !

**Comment by jtavva** [comment]
@Productivix 
Glad you were able to resolve your issue, if not please make sure you have selected the Kotlin file in the Android project pane. 

![image](https://user-images.githubusercontent.com/24260141/115449116-4b62cb00-a1cf-11eb-8f4d-8546b7df47f1.png)
