### ISSUE TITLE
Android Basics: Progress not saved - tip-calculator

### ISSUE THREAD

**Issue by fernandoapeguero** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#12]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
My Progress on the codelabs keeps getting refresh and logging me out of the developer page for some reason 

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by WisdomSays** [comment]
Use Firefox Browser instead of Chrome.

**Comment by jtavva** [comment]
@fernandoapeguero 

This issue should be resolved now.
It's been more than a month since we've heard from you, so we are going to close this issue. You can always reopen this issue or raise a new one if you need any further assistance.

**Comment by WisdomSays** [comment]
THANK YOU, ALL ISSUES HAS BEEN RESOLVED.

**Comment by jameynakama** [comment]
Just want to add that this used to happen to me, and still does. I'm using Chrome and logged in. Sometimes, I just get logged out after finishing a section (clicking "Done"). Other times, I'm still logged in but all my checkmarks are gone. It feels random.

**Comment by markHadman** [comment]
I'm getting 0% on all the pathways that I've worked through, and yes I keep seeing that I've been logged out as well. Probably worth adding that I _do_ have badges though
