### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by dega03** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#120]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#4

**In which task and step of the codelab can this issue be found?**
Section 5

**Describe the problem**
At point 5.3 this line is quoted (among others):
`        at com.example.tiptime.MainActivity.calculateTip(MainActivity.kt:22)`

however a bit later (5.6) the line number from 22 becomes 20:

`at com.example.tiptime.MainActivity.calculateTip(MainActivity.kt:20)`

**Comment by jtavva** [comment]
@dega03 
Thank you so much for reporting this issue. This is fixed and will be published soon.
