### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by SaiKummar** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#124]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#5

**In which task and step of the codelab can this issue be found?**
In the Solution code

**Describe the problem**
In RoundHut class, the residents parameter has val in front of it, which I think is unnecessary.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@SaiKummar 
Thank you for reaching out to us. The issue is fixed and will be published soon:
open class RoundHut(
       residents: Int, val radius: Double) : Dwelling(residents) {
