### ISSUE TITLE
Android Basics: change-app-icon

### ISSUE THREAD

**Issue by nicola-masarone** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#129]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-icon?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-change-app-icon#5

**In which task and step of the codelab can this issue be found?**
Change the app icon - section: Adaptive and legacy launcher icons

**Describe the problem**
Documentation typo - bad file name
![NewIssue](https://user-images.githubusercontent.com/50139878/116573647-490a1a80-a90d-11eb-912c-60dc092b80f6.png)

**_res/drawable-anydpi-v26/ic_lancher_background.xml_** 
typo for 
**_res/drawable-anydpi-v26/ic_launcher_background.xml_**

**Steps to reproduce?**
1. Go to... documentation
2. See error...

**Versions**
_Android Studio version:_ n/a
_API version of the emulator:_ n/a 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@nicola-masarone 
Thank you for reaching out to us. The typo is fixed and will be published soon.
