### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by siyamsajeebkhan** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#13]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?return=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%3Fhl%3Den%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance&hl=en#4

**In which task and step of the codelab can this issue be found?**
Step 5: Modify Classes in the Hirearchy -> Implement floorArea() for RoundHut

**Describe the problem**
It's written "The floor area of a circular dwelling is 2 * PI * radius." which is incorrect. The formula is for calculating the circumference of a circular dwelling rather than the area.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@siyamsajeebkhan 
Thank you so much for reporting this issue. This is fixed and will be published soon.
