### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by 204squares** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#130]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#4
**In which task and step of the codelab can this issue be found?**

**Describe the problem**

It's unclear why class roundhut would use 'val residents' instead of 'residents'

open class RoundHut(val residents: Int, 
    val radius: Double) : Dwelling(residents) {
   
    override val buildingMaterial = "Straw"
    override val capacity = 4

    override fun floorArea(): Double {
        return PI * radius * radius
    }
}

this is different from the previous step which showed:

class RoundHut(residents: Int) : Dwelling(residents) {
    override val buildingMaterial = "Straw"
    override val capacity = 4
}

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by sahuadarsh0** [comment]
why did you close the issue? Did you found the solution to why **val** is used...

**Comment by 204squares** [comment]
Hi adarsh, I probably didn't mean to close the issue.  Do you know the
reason?

Regards,
Justin

**Comment by sahuadarsh0** [comment]
I have raised the issue again, I think it's an error.
