### ISSUE TITLE
Android Basics: xml-layouts

### ISSUE THREAD

**Issue by Gunjan-vyas** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#134]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-xml-layouts#5

**In which task and step of the codelab can this issue be found?**
Add a Switch for rounding up the tip

**Describe the problem**
After copy and pasting the code given in the codelab for "Add a Switch for rounding up the tip" in my android studio
warning as follows 
"Warning : Use SwitchCompat from AppCompat or SwitchMaterial from Material library"

**Steps to reproduce?**
1. Go to code given in codelab for "Add a Switch for rounding up the tip" 
2. Click on it and copy the code and paste in android studio
3. See error in your android studio as "Use SwitchCompat from AppCompat or SwitchMaterial from Material library"

**Versions**
_Android Studio version:_  Android Studio 4.1.3 
_API version of the emulator:_    

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
Thank you so much for reporting this issue. This is fixed and will be published soon.
