### ISSUE TITLE
Android Basics: xml-layouts: Google Tip Calculator is gone

### ISSUE THREAD

**Issue by johnlinp** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#136]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts

**In which task and step of the codelab can this issue be found?**
2. Start the project

**Describe the problem**
The first line says:

> Check out the tip calculator on Google: https://www.google.com/search?q=tip+calculator

However, after clicking on the link, I couldn't see anything like a tip calculator:

![image](https://user-images.githubusercontent.com/1290376/117556896-56a76900-b0a0-11eb-8d7d-f4a490ad63ae.png)

**Comment by osuleymanova** [comment]
@johnlinp 
Thank you for reaching out to us. We couldn't verify the link issue. It was sent to localization team for consideration.
