### ISSUE TITLE
Android Basics: xml-layouts: "Tip Amount" TextView is not shown

### ISSUE THREAD

**Issue by johnlinp** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#137]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts

**In which task and step of the codelab can this issue be found?**
6. Complete the rest of the layout

**Describe the problem**
The screenshot shows in "Run the app" looks like:
![image](https://user-images.githubusercontent.com/1290376/117558471-557e3800-b0b0-11eb-8930-81d0c267f6b6.png)
However, it misses the `TextView` of "Tip Amount".

**Comment by osuleymanova** [comment]
@johnlinp 
Thank you for reaching out to us. The image is updated and republished.
