### ISSUE TITLE
Android Basics: xml-layouts: why can't I use match_parent inside ConstraintLayout?

### ISSUE THREAD

**Issue by johnlinp** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#139]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts

**In which task and step of the codelab can this issue be found?**
4. Build the layout in XML

**Describe the problem**
The paragraph says:

> Look at the `layout_width` attribute. It's set to `match_parent`, but you can't set `match_parent` on a child of `ConstraintLayout`.

However, when I set it to `match_parent` in my "Tip Time" app, it looks nice: its width fills up the parent perfectly.

Can this tutorial elaborate on the reason why this is not allowed? Thanks.

**Comment by jtavva** [comment]
Similar to https://github.com/google-developer-training/android-basics-kotlin-tip-calculator-app-solution/issues/34

**Comment by johnlinp** [comment]
@jtavva Is is possible to elaborate on the reason why this is not allowed? Or is it out of the scope of this tutorial?
