### ISSUE TITLE
Android Basics: change-app-icon

### ISSUE THREAD

**Issue by oezzi** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#14]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-icon?authuser=1&return=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-change-app-icon#2

**In which task and step of the codelab can this issue be found?**
3.Launcher Icons

**Describe the problem**
"For example, this is what res > mipmap-xxhdpi > ic_launcher_round.png looks like. Also notice the size of the asset is in the top right. This image is 192px x 192px in size."

it is not the xxhdpi image it is the xxxhdpi image which is 192x192 big

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
Android Studio 4.1

**Comment by jtavva** [comment]
Thank you so much for reporting this issue. This is fixed and will be published soon.
