### ISSUE TITLE
Android Basics: change-app-theme: colorSecondaryVariant should be @color/blue

### ISSUE THREAD

**Issue by johnlinp** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#140]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-theme

**In which task and step of the codelab can this issue be found?**
5. Dark theme

**Describe the problem**
In the section "Update the dark version of your theme", there are steps:

> 1. Open themes.xml (night) (app > res > values > themes > themes.xml (night))
> 2. Change colorPrimary to the light variant of the primary color you selected, @color/green_light.
> 3. Change colorPrimaryVariant to @color/green.
> 4. Change colorSecondary to @color/blue_light.
> 5. Change colorSecondaryVariant to @color/blue_light.

However, since `colorPrimaryVariant` is set to `@color/green`, `colorSecondaryVariant` should be set to `@color/blue` instead of `@color/blue_light` for the sake of symmetry.

**Comment by jtavva** [comment]
@johnlinp 
Thank you for your suggestion. 
Material Design color themes are chosen for aesthetics, accessibility, and legibility, not because of symmetry.   
Leaving the instructions in the codelab as is for now.
