### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by Fleximo** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#141]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#4

**In which task and step of the codelab can this issue be found?**
Please go to TRAINING -> ANDROID BASICS IN KOTLIN -> LAYOUTS ->
USER INPUT 1 -> 3. Classes and inheritance in Kotlin -> 5. Modify classes in the hierarchy

**Describe the problem**
Code duplication

**Steps to reproduce?**
Please have a look at: 
```
fun getRoom() {
    if (capacity > residents) {
        residents++
        println("You got a room!")
    } else {
        println("Sorry, at capacity and no rooms left.")
    }
}
```
But previously we've defined the function:
```
fun hasRoom(): Boolean {
        return residents < capacity
}
```
So maybe it is make sense to replace
`capacity > residents` to` hasRoom()`
And we would get:
```
fun getRoom() {
    if (hasRoom()) {
        residents++
        println("You got a room!")
    } else {
        println("Sorry, at capacity and no rooms left.")
    }
}
```

**Versions**
_Android Studio version:_  NO
_API version of the emulator:_ NO 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@Fleximo 
Thank you for the suggestion.
Added the following note below the code block. 

> Tip: In the above code block, you can replace the  if condition to use hasRoom() function: if(hasRoom()) {...}. The hasRoom() function defined above compares the resident capacity to the number of residents.

This is fixed and will be published soon.
