### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by yurii-harkusha** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#144]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance

**Describe the problem**
Problem with "Dark/Light theme" button visibility in Dark mode

**Steps to reproduce?**
1. https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance
2. Click on Dark/Light code button
3. Icon is invisible 

Seems like this problem is common for all codelab pages with code snippet

<img width="1243" alt="Знімок екрана 2021-05-12 о 14 56 53" src="https://user-images.githubusercontent.com/5817271/117975356-452bbe80-b337-11eb-86ed-4f37c2c57383.png">
<img width="1336" alt="Знімок екрана 2021-05-12 о 14 57 03" src="https://user-images.githubusercontent.com/5817271/117975364-478e1880-b337-11eb-9704-48b7f78fc45f.png">

**Comment by osuleymanova** [comment]
@yurii-harkusha 
Thank you for reaching out to us. The issue is fixed and published. The dark/light code theme icon is visible now.
