### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by danielcesarini** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#146]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#1

**In which task and step of the codelab can this issue be found?**
2. What is a class hierarchy?

**Describe the problem**
At the end of the page 
<<Learn more here.

57cd75bd819126bb.png <-- this image is broken

As you can see, learning to leverage inheritance among classes can make your code easier to write, reuse, read, and test.>>

**Additional information**
![image](https://user-images.githubusercontent.com/39871901/118316754-7e129180-b4f7-11eb-895b-b27bec0dedaa.png)

**Comment by osuleymanova** [comment]
@danielcesarini 
Thank you for reaching out to us. The issue is fixed and published.
