### ISSUE TITLE
Android Basics: polished-user-experience

### ISSUE THREAD

**Issue by giovanniguzman** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#147]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-polished-user-experience?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-polished-user-experience#5

**In which task and step of the codelab can this issue be found?**
In the task: (Optional) Adjust the tint of the vector drawables

**Describe the problem**
There are some images, for instance, the bdddc76d0ca06573.png is not displayed, instead, a broken icon image is displayed.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@giovanniguzman 
I thank you for bringing this issue to our attention. Now it is fixed and published.
