### ISSUE TITLE
Android Basics: change-app-theme

### ISSUE THREAD

**Issue by takhau** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#148]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-theme#4vv

**In which task and step of the codelab can this issue be found?**
Update the dark version of your theme

**Describe the problem**
The sample themes.xml (night) doesn't as as the description.
        <item name="colorSecondaryVariant">@color/blue_light</item>
should be 
        <item name="colorSecondaryVariant">@color/blue</item>

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@takhau 
Thank you for reaching out to us. We added the Note that colorSecondaryVariant could  be the same color as colorSecondary. It will be published soon.
