### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by TheWeenhayek** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#15]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?authuser=1#4

**In which task and step of the codelab can this issue be found?**
Step 5

**Describe the problem**
It's just a problem in the concept of circular area, you say: "The floor area of a circular dwelling is 2 * PI * radius" but the area is pi*r^2 and what you said is the perimeter... Probably it's just a minor mistake but I hope it helps to improve your course which so far is the best i have taken

**Comment by jtavva** [comment]
Thank you so much for reporting this issue. This is fixed and will be published soon.
