### ISSUE TITLE
Android Basics: polished-user-experience

### ISSUE THREAD

**Issue by KKH-tw** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#152]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-polished-user-experience#3

**In which task and step of the codelab can this issue be found?**
Support older Android versions

**Describe the problem**
It seems that the phrase in the parenthesis "(known as backwards compatibility)" should be "(known as backward compatibility)", since the word describing the noun should be an adjective.

**Steps to reproduce?**
As stated above.

**Versions**
Not applicable.

**Additional information**
Nil.

**Comment by osuleymanova** [comment]
@KKH-tw 
Thank you for reaching out to us. The most common usage is backward compatibility. But according to Wikipedia [https://en.wikipedia.org/wiki/Backward_compatibility] both variants can be used,(https://screenshot.googleplex.com/7dxVV5naWb4o5cw.png) so there is no need to make edits in the codelab.
