### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by EthanHatch** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#155]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#2

**In which task and step of the codelab can this issue be found?**
Step 3: View Binding

**Describe the problem**
The tutorial asks the user to add the following to the android section of their module gradle:
buildFeatures {
    viewBinding = true
}

This is out of date and results in confusing gradle errors.
After some time I found the answer to be: 

viewBinding {
enabled true
}

Please fix this and keep up the awesome tutorials!

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@EthanHatch 
Thank you for reaching out to us.
The correct syntax to enable the viewBinding is as follows (as mentioned in the codelab):

buildFeatures {
        viewBinding = true
    }
Please use the above code and let us know if you are still facing issues.
