### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by sahuadarsh0** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#157]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#4

**In which task and step of the codelab can this issue be found?**
1. Modify classes in the hierarchy - Implement floorArea() for RoundHut
2. Modify finished code

**Describe the problem**
At step 3 of Implement floorArea() for RoundHut step, the code is:

```
open class RoundHut(
   val residents: Int, 
   val radius: Double) : Dwelling(residents) {
   /* code */
}
```
What I think is wrong is that residents is being declared again. Residents is from Dwelling abstract class, the root class. Testing the code without declaring residents, like this, works the same way

```
open class RoundHut(
   residents: Int, 
   val radius: Double) : Dwelling(residents) {
   /* code */
}

```

And After Step 8 **Finished Code** we have the same issue
```
 /* code */
open class RoundHut(
   val residents: Int, 
   val radius: Double) : Dwelling(residents) {
   /* code */
}
 /* code */
```

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
1st
![image](https://user-images.githubusercontent.com/25864174/120068334-bd1b1800-c09d-11eb-83a7-58bed901f178.png)

2nd
![image](https://user-images.githubusercontent.com/25864174/120068345-d328d880-c09d-11eb-83fc-8c76c6a0a57f.png)

**Comment by osuleymanova** [comment]
@sahuadarsh0 
Thank you for reaching out to us. The issue is fixed and will be published soon.
