### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by FJavier1962** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#158]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

Switch is deprecated now androidx.appcompat.widget.SwitchCompat is used

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_  4.2.1
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@FJavier1962 
Thank you for reaching out to us. The content of the codelab is up-to-date.
