### ISSUE TITLE
Android Basics: change-app-icon

### ISSUE THREAD

**Issue by Ult1Gamer** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#16]
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-icon?return=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-change-app-icon#2

In Unit 2: Layouts, Step 7: Change the app icon, there is a spelling mistake in the last **Note**: "closet", which should be "closest"

Otherwise this is great work!

**Comment by jtavva** [comment]
Thank you so much for reporting this issue. This is fixed and will be published soon.
