### ISSUE TITLE
Android Basics: xml-layouts

### ISSUE THREAD

**Issue by os4ma31** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#160]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-xml-layouts#4

**In which task and step of the codelab can this issue be found?**
codelab: Create XML layouts for Android
step: (5) add tip optons

**Describe the problem**
In the end of the step (solution code)
in "<RadioButton
            android:id="@+id/option_fifteen_percent"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            **android:text="OK (15%)" />** "

android text is equal to  "OK"
but in the photo it is "Okay"

this is small mistake but worth mentioning

![image](https://user-images.githubusercontent.com/85602109/121295507-3ae1ed80-c900-11eb-86d0-ec797d3c4eba.png)
![image](https://user-images.githubusercontent.com/85602109/121295559-4c2afa00-c900-11eb-86e3-078f9adfbb9f.png)
![image](https://user-images.githubusercontent.com/85602109/121295626-682e9b80-c900-11eb-9dca-b944400d8368.png)

**Comment by osuleymanova** [comment]
@os4ma31 
Thank you for reaching out to us. The typo is fixed and will be published soon:

![Screen Shot 2022-09-13 at 10 10 37 AM](https://user-images.githubusercontent.com/86437155/189964717-21a2e920-0282-4586-9cf1-ad1a4bd719f9.png)

The images will be updated as well.
