### ISSUE TITLE
Android Basics: change-app-icon

### ISSUE THREAD

**Issue by Maximgbb** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#161]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-icon?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-change-app-icon#5

**In which task and step of the codelab can this issue be found?**
Step 6 ¨Change the app icon¨ - Move vector drawable files into -v26 directory

**Describe the problem**
it says that ¨you may notice that the **foreground** asset is located in the **drawable-v24 folder**, while the **background** asset is in the **drawable** folder.¨, but the background is the one inside drawable-24 folder, not the foreground.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
Android Studio 4.2.1
Build #AI-202.7660.26.42.7351085, built on May 10, 2021
Runtime version: 11.0.8+10-b944.6916264 x86_64
VM: OpenJDK 64-Bit Server VM by N/A
macOS 10.16
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: external.system.auto.import.disabled=true

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@Maximgbb 
The issue that you presented to us is extremely important, and I thank you for bringing it to our attention. The content is updated and will be published soon.
