### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by Woepps** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#167]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#2

**In which task and step of the codelab can this issue be found?**
task 3 "View Binding"

**Describe the problem**
Adding the buildFeatures{viewBinding true} to build.gradle file gives an error because method buildFeatures is unknown. Seems 
to have been changed somewhen to viewBinding {enabled true}.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 3.6.3
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@Woepps 
Thank you for reaching out to us. The error message could appear if one of the steps provided in the codelab was missed. Please try to do as described:
![Screen Shot 2022-03-23 at 3 49 18 PM](https://user-images.githubusercontent.com/86437155/159809256-0b680285-29dd-44dc-9752-a853abbcde2a.png)
Happy coding!
