### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by Error404Coder** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#169]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#4

**In which task and step of the codelab can this issue be found?**
5th part of the codelab, floorArea for RoundTower()

**Describe the problem**
Earlier, the tutorial said that the residents variable should not have the "val" since residents can change over time. This is true for the Step 4 of the codelab. Suddenly, it changed in the Part 5. The residents parameter is a variable hence the "val" there should be omitted.

**Steps to reproduce?**
1. Go to the classes-and-inheritance tutorial for Android.
2. Click on the fourth step and the fifth step. 
3. See error in comparing the two roundHut parameters.

**Versions**
Current codelab as of June 30,2021 4:15 AM

**Additional information**
![image](https://user-images.githubusercontent.com/20508814/123860247-3e452380-d958-11eb-8e4d-773b9e1e31cf.png)
Step/Part 5 Solution for floorArea function of roundHut (with val in residents parameter)

![image](https://user-images.githubusercontent.com/20508814/123861540-e1e30380-d959-11eb-979c-f87c4af8c1b9.png)
Step/Part 4 Last code (without val in residents parameter)

Note: This might not be a big of a deal but I just want to report it.
Maybe I'm wrong but I'm quite sure that the val there should be omitted.

Thank you for your time.

**Comment by osuleymanova** [comment]
@Error404Coder 
Thank you for reaching out to us. The typo is fixed and will be published soon:

![Screen Shot 2022-06-27 at 5 11 25 PM](https://user-images.githubusercontent.com/86437155/176060718-55e362d5-0fc5-4a19-aeb5-e8d5d5aca822.png)
