### ISSUE TITLE
Android Basics: change-app-icon

### ISSUE THREAD

**Issue by artnkfv** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#17]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-icon#5

**In which task and step of the codelab can this issue be found?**

       steps 4 and 5 in "Move vector drawable files into -v26 directory"

**Describe the problem**

       Description of steps 4 and 5 in "Move vector drawable files into -v26 directory" is incorrect

**Steps to reproduce?**
1. Go to step 13(Confirm icon path..)

2. zoom up picture below step 13,check the folder for foreground and background xmls.
      ic_launcher_background.xml - is in drawable-v24 
      ic_launcher_foreground.xml - is in drawable

3. go to step "Move vector drawable files into -v26 directory".

4 .steps 4 and 5 tells u that  
        ic_launcher_background.xml - is in drawable 
        ic_launcher_foreground.xml - is in drawable-v24
   It should be vice versa(folders for launcher layers) in android studio its also vice versa.
![icon layers folders](https://user-images.githubusercontent.com/42325809/96931936-c9674300-14c6-11eb-92ba-baa5a6072db8.png)
![incorect_description](https://user-images.githubusercontent.com/42325809/96931939-c9ffd980-14c6-11eb-8a75-f5b40305a47d.png)

(Left click on the ic_launcher_background.xml file and drag it from the drawable folder into the drawable-anydpi-v26 folder. Recall that putting a resource in an "any dpi" directory indicates that it's a resource that can scale to any density.
Left click on the ic_launcher_foreground.xml and drag it from the drawable-v24 folder into the drawable-anydpi-v26 folder.)

**Versions**
_Android Studio version:_ 4.1
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@artnkfv 
Thank you so much for reporting this issue. This is fixed and will be published soon.
