### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by sankar2907** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#170]
**URL**  : https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#2

**Enable view binding 

- Open the app's build.gradle file ( Gradle Scripts > build.gradle (Module: Tip_Time.app) )

- In the android section, add the following lines:

buildFeatures {
    viewBinding = true
}**

I think this link of code should be 
buildFeatures {
    viewBinding true
}
replaced with

viewBinding {
    enabled true
}

**Comment by osuleymanova** [comment]
@sankar2907 
Thank you for reaching out to us. The code snippet provided in the codelab is correct. The ticket is closed as no further actions required.
