### ISSUE TITLE
Android Basics: change-app-theme

### ISSUE THREAD

**Issue by Fleximo** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#174]
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-theme?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-change-app-theme#2
 
On step 4 we can see the usage of **colorPrimaryDark** attribute. This attribute wasn't mentioned in the tutorial under (12 named attributes: colorPrimary, colorPrimary Variant, colorSecondary, etc.)
![Screenshot_20210704-154155](https://user-images.githubusercontent.com/6609408/124385703-97f27880-dcdf-11eb-9e3d-a85b3337049e.png)

On step 5 screenshot we can see the usage of **colorPrimaryVariant**
![Screenshot_20210704-154218](https://user-images.githubusercontent.com/6609408/124386276-59aa8880-dce2-11eb-81e2-3a095c047d11.png)

Solution: Looks like **colorPrimaryDark** should be replaced to **colorPrimaryVariant**

**Comment by osuleymanova** [comment]
@Fleximo 
Thank you for reaching out to us. The issue is fixed and will be published soon.
