### ISSUE TITLE
Android Basics: xml-layouts

### ISSUE THREAD

**Issue by rexsace** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#177]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-xml-layouts#4

**In which task and step of the codelab can this issue be found?**
5. Add tip options

**Describe the problem**
In step 10, under the first set of steps, the description tells to set orientation to "horizontal". However, in the sample XML, the orientation is set to "vertical".

**Steps to reproduce?**
Open section of codelab, and go to step 10.

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/30991539/124899831-1407fb80-e013-11eb-84a5-b3599a91a05f.png)

**Comment by osuleymanova** [comment]
@rexsace 
Thank you for reaching out to us. The code provided in the codelab is correct:

![Screen Shot 2022-09-12 at 2 39 18 PM](https://user-images.githubusercontent.com/86437155/189763692-f998cc84-79c9-40ff-92c5-9181392e5862.png)

There are 2 options to make RadioButtons in a column or in a row. The android:orientation ="horizontal" is applicable if you want to change the orientation and make the RadioButtons in a row.
