### ISSUE TITLE
Android Basics: Done/Next button is missing - change-app-icon

### ISSUE THREAD

**Issue by artnkfv** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#18]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-icon#8

**In which task and step of the codelab can this issue be found?**
Last step
9. Learn more

**Describe the problem**

"DONE" button missing

**Steps to reproduce?**
When i try to reproduce steps its work well but in new tub .

**Versions**
_Android Studio version:_ 4.1
![done_button](https://user-images.githubusercontent.com/42325809/96935299-72fd0300-14cc-11eb-8c32-ef34b2f39afe.png)
[developer.android.com-1603404335200.log.log](https://github.com/google-developer-training/android-basics-kotlin-tip-calculator-app-solution/files/5426184/developer.android.com-1603404335200.log.log)

[bandicam 2020-10-23 00-55-03-926.zip](https://github.com/google-developer-training/android-basics-kotlin-tip-calculator-app-solution/files/5426192/bandicam.2020-10-23.00-55-03-926.zip)

_API version of the emulator:_ 

**Additional information**

Microsoft Edge
Version 86.0.622.48 (Official build) (64-bit)

**Comment by osuleymanova** [comment]
@artnkfv 
Thank you for reporting this issue. It was fixed and published
