### ISSUE TITLE
Android Basics: change-app-theme

### ISSUE THREAD

**Issue by MIklgr500** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#180]
[3. Themes](https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-theme?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-change-app-theme#2)

**Create an Empty Activity project**
After copy-paste .XML code on android studio ide alarm about the error in code because it doesn't have in dependencies "com.google.android.material".  I'm decide this problem with insert on dependencies `implementation 'com.google.android.material:material:1.5.0-alpha01` 
For my mind will be helpful add some hint about this.

```
Android Studio 4.2.2
Build #AI-202.7660.26.42.7486908, built on June 24, 2021
Runtime version: 11.0.8+0-b944-P17168821 amd64
VM: OpenJDK 64-Bit Server VM by N/A
Linux 5.4.0-77-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 4
Registry: external.system.auto.import.disabled=true

Current Desktop: ubuntu:GNOME
``

**Comment by osuleymanova** [comment]
@MIklgr500 
Thank you for reaching out to us and reporting your concern. With the latest Android Studio Bumblebee version, it's already imported by default so no need to update the codelab content.
