### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by eliyahillel** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#182]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#4

**In which task and step of the codelab can this issue be found?**
Test and debug -> debug the crash -> 4

**Describe the problem**

I'm pretty sure there's a word missing and it should be "and the rest tells you" (unless my English isn't good enough to understand)

![image](https://user-images.githubusercontent.com/73447394/125604168-908c1778-7670-4d1e-885d-dd72d5d1c187.png)

**Steps to reproduce?**
1. Go to... the second paragraph on the 4th step
2. Click on... nothing
3. See error... just like the included image 

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@eliyahillel 
Thank you for reaching out to us. The issue is fixed and published.

**Comment by eliyahillel** [comment]
Nice

בתאריך יום ג׳, 23 בנוב׳ 2021, 3:01, מאת osuleymanova ‏<
***@***.***>:
