### ISSUE TITLE
Android Basics: xml-layouts

### ISSUE THREAD

**Issue by CaptainThunk** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#183]
https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-xml-layouts#3

4. Build The Layout in XML

The last example of what the code should look like has dropped the 'android:padding="16dp"' from the constraint layouts attributes. It is present in the earlier ones.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@CaptainThunk 
Thank you for reaching out to us. The issue is fixed and will be published soon.
