### ISSUE TITLE
Android Basics: change-app-icon

### ISSUE THREAD

**Issue by sverma29** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#184]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-icon#5

**In which task and step of the codelab can this issue be found?**
Point 2. Create a new Image Asset. You could right click on the res directory and choose New > Image Asset. Or you can click on the Resource Manager tab, click the + icon, and select Image Asset.

**Describe the problem**
Right click has to be done on drawable folder and not the res folder as mentioned in order to get proper assets in the mipmap folder and to have ic_launcher_background.xml in the drawable folder and ic_launcher_foreground.xml in the drawable-v24 folder.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version: 4.2.2
_API version of the emulator: 30 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@sverma29 
Thank you for reaching out to us. The content is updated and will be published soon.
