### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by Gyanendra011Yadav-coder** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#185]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#2

**In which task and step of the codelab can this issue be found?**
In Enabling View Binding.

**Describe the problem**
buildFeatures {
    viewBinding = true
}

this,  is not accepting but when i chnaged it to

buildFeatures.viewBinding=true
                                                     ,, it works pls mark this method, as i suffred a lot due to this error was trying to solve from last 2 days, but on 3rd day i got this approach

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@Gyanendra011Yadav-coder 
Thank you for reaching out to us. We appreciate your feedback.
