### ISSUE TITLE
Android Basics: polished-user-experience

### ISSUE THREAD

**Issue by AndroidDude123** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#186]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-polished-user-experience?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-polished-user-experience#2

**In which task and step of the codelab can this issue be found?**
Material Componet. I followed everything up to 8.

**Describe the problem**
When I added to the line

val stringInTextField = binding.costOfServiceEditText.text.toString()

                                                                                      ^
                                                                                     .text is highlighted and I cannot compile the program.
I followed every step. I been playing around to see if I can fix " .text" by changing it into " .getText" or right-click and create extension property -> TextInputLayout.text and crashes the program even more. I cannot for the life of me progress.

**Steps to reproduce?**
1. Go to... create a more polished user experience and follow every step of the way up to 8.
2. Click on... goto MainActivity.kt right-click on highlighted .text
3. See error...

**Versions**
_Android Studio version:_ 4.2.2
_API version of the emulator:_  Pixel 3XL API 29
![red-underline( text)](https://user-images.githubusercontent.com/86205178/127238121-61212df4-f901-48b9-a7cf-73de9f286bd3.jpg)
![red-underline( text)2](https://user-images.githubusercontent.com/86205178/127238251-621da228-2af0-43b7-95b9-2a14a92bedcd.jpg)

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@AndroidDude123 
Thank you for reaching out to us and providing the screenshots. One of the solutions is to add:
 `binding.costOfServiceEditText.setOnKeyListener`  above `private fun calculateTip()` so the final code should look like this:
![Screen Shot 2022-03-31 at 3 48 48 PM](https://user-images.githubusercontent.com/86437155/161162308-3a6afdca-55d0-4bfb-8963-310d2e267331.png)
Hope it helps to solve your error. If not, please feel free to reopen the ticket providing more details. 
Happy coding!
