### ISSUE TITLE
Android Basics: change-app-icon

### ISSUE THREAD

**Issue by bybybybybyby** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#187]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-icon?authuser=5&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%3Fauthuser%3D5%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-change-app-icon#5

**In which task and step of the codelab can this issue be found?**
6. Change the app icon
-Move vector drawable files into -v26 directory

**Describe the problem**
In the following paragraph, the explanation reverses the foreground asset and background asset, regarding which contains a gradient and the folders they will be found in.

"Depending on the min SDK of your app, you may notice that the foreground asset is located in the drawable-v24 folder, while the background asset is in the drawable folder. The reason is because the foreground asset contains a gradient, which was available starting in the Android 7.0 release (also known as API version 24, hence the -v24 resource qualifier). The background asset doesn't contain a gradient, so that can go in the base drawable folder."

**Steps to reproduce?**
1. Go to... Project Files > app > src > res
2. Click on... drawable folders
3. See error...  notice the foreground and background assets compared to the explanation

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@bybybybybyby 
Thank you for reaching out to us. The typo is fixed and published:

![Screen Shot 2022-09-14 at 2 07 35 PM](https://user-images.githubusercontent.com/86437155/190275902-f1df512a-3e13-46cb-accb-a99f11e19753.png)
