### ISSUE TITLE
Android Basics: xml-layouts

### ISSUE THREAD

**Issue by ikura1** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#188]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts#5

**In which task and step of the codelab can this issue be found?**
6. Complete the rest of the layout
Add a Switch for rounding up the tip

**Describe the problem**
Characters that should not be coded are coded.

"As noted above, set the `layout_width` to `0dp.`"

**Steps to reproduce?**
1. Go to https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts#5
2. Go to Step1 `Add a Switch for rounding up the tip`
3. See text "As noted above, set the `layout_width` to \`0dp.`"

**Comment by osuleymanova** [comment]
@ikura1 
Thank you for reaching out to us. The issue is fixed and published.
