### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by ladylazy9x** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#193]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#5

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
why we can use "val" and without "val" for residents??
`open class RoundHut(
       val residents: Int, val radius: Double) : Dwelling(residents) {

   override val buildingMaterial = "Straw"
   override val capacity = 4

   /**
    * Calculates floor area for a round dwelling.
    *
    * @return floor area
    */
   override fun floorArea(): Double {
       return PI * radius * radius`

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@ladylazy9x 
Thank you for reaching out to us. The typo is fixed and will be published soon:

![Screen Shot 2022-06-27 at 5 11 25 PM](https://user-images.githubusercontent.com/86437155/176060144-70213cc8-776e-4b3e-86db-f98fd50b4936.png)
