### ISSUE TITLE
Android Basics: change-app-icon

### ISSUE THREAD

**Issue by CauselessDusty** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#198]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-icon#5

**In which task and step of the codelab can this issue be found?**
6 -> Move vector drawable files into -v26 directory

**Describe the problem**
In the codelab the information for foreground and background are swapped in the paragraph under the section "Move vector drawable files into -v26 directory" One example is that it mentions that the foreground has a gradient where the background is the one with the gradient.

**Steps to reproduce?**
1. Go to... the url and scroll to section "Move vector drawable files into -v26 directory"
2. Click on... 
3. See error... 

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
![image](https://user-images.githubusercontent.com/22016262/129451960-f54ebcc6-4d93-4f95-8080-762b8915be87.png)

![image](https://user-images.githubusercontent.com/22016262/129451919-d8692ea9-3fec-4ae7-8a0f-fbd4ce32ce03.png)

**Comment by osuleymanova** [comment]
@CauselessDusty 
Thank you for reaching out to us. The typo is fixed and published:

![Screen Shot 2022-09-14 at 2 07 35 PM](https://user-images.githubusercontent.com/86437155/190263214-519bc357-520e-404b-b0b9-424c8e3f3cf6.png)
