### ISSUE TITLE
Android Basics: polished-user-experience

### ISSUE THREAD

**Issue by artnkfv** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#20]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-polished-user-experience?return=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-polished-user-experience#5

**In which task and step of the codelab can this issue be found?**

(Optional) Adjust the tint of the vector drawables

**Describe the problem**
Typo in text

**Steps to reproduce?**
1. Go to... (Optional) Adjust the tint of the vector drawables
2. In text bellow Grey bell image
3. See error... 

**Versions**
_Android Studio version:_ 4.1
![typo](https://user-images.githubusercontent.com/42325809/97094511-eb46fe00-165d-11eb-96e9-b7cd14f4e143.png)

_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@artnkfv 
Thank you so much for reporting this issue. This is fixed and will be published soon.
