### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by mutoxu-N** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#203]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?hl=ja&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%3Fhl%3Dja%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#2

**In which task and step of the codelab can this issue be found?**
Enable view binding

**Describe the problem**
In my environment, this code doesn't work.
```
buildFeatures {
    viewBinding = true
}
```

Next code works correctly instead.
```
buildFeatures {
    viewBinding true
}
```

**Versions**
_Android Studio version:_ Android Studio Arctic Fox | 2020.3.1
Build #AI-203.7717.56.2031.7583922, built on July 27, 2021
_API version of the emulator:_  19

**Comment by osuleymanova** [comment]
@mutoxu-N 
Thank you for reaching out to us. If you are using the Groovy for gradle scripts in this case your suggested solution to remove the equal sign works well. For Kotlin gradle the code snippet provided in the codelab is correct. Hope this clarifies the situation.
Happy coding!
