### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by griffinevo** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#210]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#3

**In which task and step of the codelab can this issue be found?**
Display the tip, step 3

**Describe the problem**
Code suggested is 
`    binding.tipResult.text = getString(R.string.tip_amount, formattedTip)`
but this doesn't work. A small change works:
`    binding.tipResult.text = getString(R.string.tip_amount) + formattedTip`

**Steps to reproduce?**
Paste the code from the code lab, problem is highlighted in red in IntelliJ

**Versions**
_Android Studio version:_  Using IntelliJ 2021.1.1
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@griffinevo 
Thank you for reaching out to us.
As for the error highlighted in red we appreciate if you share the screenshot of it as we couldn't observe it on our side:

![Screen Shot 2022-09-14 at 11 04 10 AM](https://user-images.githubusercontent.com/86437155/190229865-64249212-d8f2-4a8b-b88f-62bc28228e78.png).

Please feel free to reopen the ticket with the requested screenshot
