### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by kgabriel113** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#216]
**Codelab Link**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator

Task 3: View Binding, step 2 of "Enable View Binding"

**Issue Description**
The sample code for enabling view binding looks like 
`buildFeatures {
    viewBinding = true
}`
but this doesn't work and Android Studio shows the gradle error "Access to 'viewBinding' exceeds its access rights". Removing the equals sign removes the error and gradle is then able to sync correctly.

**Steps to reproduce**
1. Go to the build.gradle file for Module:Tip_Time.app
2. Add `viewBinding = true` to the buildFeatures {} section within android {} section
3. See error "Access to 'viewBinding' exceeds its access rights"
4. Removing the equals sign from `viewBinding = true` removes the error.

**Versions**
_Android Studio version:_ Android Studio Arctic Fox | 2020.3.1 Patch 2
_compileSdk:_ 31

**Screenshots**
Example code:
![viewBinding_instruction](https://user-images.githubusercontent.com/47282619/135915811-940e9f0b-bae8-4930-a264-484f22665837.png)
Error message
![viewBinding_error](https://user-images.githubusercontent.com/47282619/135915824-62e233c7-1e89-4b44-ade9-500b6f58e8c4.png)
No error message
![viewBinding_correct](https://user-images.githubusercontent.com/47282619/135915831-ea708c34-5811-4449-aa1e-86433629a9d6.png)

**Comment by osuleymanova** [comment]
@kgabriel113 
Thank you for reaching out to us. This error message "Access to 'viewBinding' exceeds its access rights" could happen if you are using the Groovy for gradle scripts. In this case your suggested solution to remove the equal sign works well. For Kotlin gradle the code snippet provided in the codelab is correct. Hope this clarifies the situation.
Happy coding!
