### ISSUE TITLE
Android Basics: xml-layouts

### ISSUE THREAD

**Issue by sharma01ketan** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#218]
(  https://bit.ly/2Z46DK1  )
**URL of codelab**

**Found in:**
In the 
Task number 4, of the A'[Build The Layout in XML](https://bit.ly/3pfLp6J)'
Inside that, In the 'Delete the TextView' topics', point number 2.

Android Developer Training>[Android Basics in Kotlin](https://bit.ly/3DV9SCs)>Unit 2 (Layouts)>Pathway 1(Get User Input in an App)>Task 4(Create XML layouts for Android)>Codelab 4([Build The Layout in XML](https://bit.ly/3pdfbt1))>Delete the TextView>Point 2

**In which task and step of the codelab can this issue be found?**

<img width="1437" alt="android developer problem" src="https://user-images.githubusercontent.com/81684683/137866106-32bbcd53-2079-4f01-b7a6-24ae9cad8ec6.png">

Here we are told to add 16dp padding to the ConstraintLayout, after the 'android:padding="16dp"' is not visible/shown in any of the 'code snippets' before the solution code provided in the [part 8](https://bit.ly/3vqjMZJ) of the same code lab ( https://bit.ly/3ASvb5F )

**Describe the problem**

There are no steps to reproduce as the error is in the documentation only.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by sharma01ketan** [comment]
I am learning android development through Google Codelab based learning module, 'Android Basics in Kotlin' and noticed that a line of code was missing in a few code snippets, the problem wasn't a restriction in learning the concept though.

**Comment by osuleymanova** [comment]
@sharma01ketan 
Thank you for reaching out to us. The code snippets are updated and will be published soon.
