### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by BarbosSergos** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#22]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?return=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#7

**In which task and step of the codelab can this issue be found?**
8. Summary

**Describe the problem**
Mistype in attribute name: checkRadioButtonId instead of checkedRadioButtonId

**Steps to reproduce?**
1. Go to URL of codelab
2. Click on line: "Use the checkRadioButtonId attribute of a RadioGroup to find which RadioButton is selected"
3. See erro.

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@BarbosSergos 
Thank you so much for reporting this issue. This is fixed and will be published soon.
