### ISSUE TITLE
Android Basics: xml-layouts

### ISSUE THREAD

**Issue by bright943nw** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#221]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-xml-layouts#3

**In which task and step of the codelab can this issue be found?**
Task 4, the last step

**Describe the problem**
There is no string "android:padding="16dp" in constraint layout

![screenshot_0005](https://user-images.githubusercontent.com/56880306/138593766-f833ae0a-a066-426a-9802-808c1bbb1a3c.jpg)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@bright943nw 
Thank you for reaching out to us. The issue is fixed and will be published soon.
