### ISSUE TITLE
Android Basics: polished-user-experience

### ISSUE THREAD

**Issue by jquinterom** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#227]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-polished-user-experience#2

**In which task and step of the codelab can this issue be found?**
The mistake is in step 3 Material Components

**Describe the problem**
This problem is encountered when someone presses and clicks the first "switches" link, after the Switches subtitle. This link opens in another tab, but doesn't open the section switches, otherwise the checkboxes section. 

**Steps to reproduce?**
1. Go to this link (https://developer.android.com/codelabs/basic-android-kotlin-training-polished-user-experience#2)
2. Go down to the switches section
3. Click on the first link "switches"
4. See the URL and wait a moment
3. See that this link shows the checkboxes section and not the switches.

**Versions**
_Android Studio version: 4.1
_API version of the emulator: 29

**Additional information**
![image](https://user-images.githubusercontent.com/87286568/138994076-c8e304dd-e869-42b1-8f6b-f9d65fcfe306.png)

Loading page:
![image](https://user-images.githubusercontent.com/87286568/138994163-1856393f-b94b-4b22-a05c-f9829db48919.png)

After that:
![image](https://user-images.githubusercontent.com/87286568/138994224-c98607d8-bda3-4fbb-94ab-b814cd0e14ae.png)

**Comment by osuleymanova** [comment]
@jquinterom 
Thank you for reaching out to us. The issue is fixed and published.
