### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by wmokrogulski** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#23]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
Instead of 'The floor area of a circular dwelling is 2 * PI * radius.'
should be 'The floor area of a circular dwelling is PI * radius * radius'

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/45422424/97638462-da6f0180-1a3c-11eb-8614-292d903e7d62.png)

**Comment by jtavva** [comment]
@wmokrogulski 
Thank you so much for reporting this issue. This is fixed and will be published soon.
