### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by kev-carmichael** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#231]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#3

**In which task and step of the codelab can this issue be found?**
Layouts > User Input 1 > 5 Calculate the Tip > Step 4

**Describe the problem**
calculateTip method should contain the following line 
val stringInTextField = binding.costOfServiceEditText.text.toString()
NOT
val stringInTextField = binding.costOfService.text.toString()

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @kev-carmichael,

Thank you for reaching out to us and reporting this typo. It is fixed:
![Screenshot 2023-03-31 at 3 58 48 PM](https://user-images.githubusercontent.com/86437155/229247369-1416cbc2-0d49-4529-a773-7ae984622671.png)
