### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by Metalicat** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#232]
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#4

Part 5, when debugging and reading the Logcat

The error indicates line 22, however, at step 7:

*Look carefully at that line, and you can see exactly where in your code the call was made, **line 20** in MainActivity.kt.*
The log indicates line 22, not 20.
![image_2021-11-05_171405](https://user-images.githubusercontent.com/80319426/140542921-94e16283-a1ba-4f95-b65e-9001c8e5c7e3.png)

**Comment by osuleymanova** [comment]
@Metalicat 
Thank you for bringing this typo to our attention. Actions will soon be taken to fix it.
