### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by diskostu** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#233]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
Near the end :)

**Describe the problem**
A code example is given:
```Kotlin
override val capacity = 4 * floors
```
This is kind of static code. Wouldn't it be better to write this:
```Kotlin
override val capacity = super.capacity * floors
```

**Comment by osuleymanova** [comment]
@diskostu 
Thank you for reaching out to us and sharing your feedback.
