### ISSUE TITLE
Android Basics: change-app-icon - contradicting text in step 6

### ISSUE THREAD

**Issue by SyedAhmedJamil** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#235]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-icon

**In which task and step of the codelab can this issue be found?**
Step 6 - Change the app icon
Task - Move vector drawable files into -v26 directory

**Describe the problem**
The screenshot shows the foreground asset in `drawable` folder and the background asset in `drawable-v24` folder which is correct.

![image](https://user-images.githubusercontent.com/26192922/141660142-ea9d9e6d-567e-4b43-8a17-98b679acd4d7.png)

But the _**Move vector drawable files into -v26 directory**_ section text says otherwise, that foreground asset is in `drawble-v24` folder and background text is in `drawable` folder which can be confusing to the reader

![image](https://user-images.githubusercontent.com/26192922/141660333-2835a3a7-51ee-43fb-a0d6-a10d42a5d685.png)

**Steps to reproduce?**
1. Go to the codelab from the link given above
2. Click on step 6 - change app icon 
3. See section - **_Move vector drawable files into -v26 directory_**

**Comment by osuleymanova** [comment]
@SyedAhmedJamil 
Thank you for reaching out to us. The codelab content is updated and will be published soon.
![Screen Shot 2022-03-28 at 5 10 06 PM](https://user-images.githubusercontent.com/86437155/160507445-eef5ebe0-a3b8-4dc3-9632-194661d95496.png)
