### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by Kemenike** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#237]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#3

**In which task and step of the codelab can this issue be found?**
When compiling the app, with View Binding, there is a compile error where you cannot run the app with the Gradle build.

**Describe the problem**
When compiling the app, with View Binding, you have to revert the Gradle build back to 1.6.0. If there is a way around the 
"A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade" error I think a note would be helpful and or a method to remove the error for 1.7.0 Gradle build.

**Steps to reproduce?**
1) Follow current instructions with Gradle build 1.7.0
2) Compile.
3) Cry because you did everything correct. (Maybe I missed a step.)

**Versions**
_Android Studio version:_  2020.3.1 Patch 2
_API version of the emulator:_  Nexus API 30

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
Gradle build 1.7.0 

 -> I don't have a picture of the problem. I just know under the build log it says something about an AARMetaData error.

**Comment by osuleymanova** [comment]
@Kemenike 
Thank you for reaching out to us. As the latest Kotlin version 1.6.0 was released recently try the version 1.5.31 first, don't forget to resync. If it doesn't help please come back to us reopening the issue.
Happy coding!
