### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by joel16** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#239]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#5

**In which task and step of the codelab can this issue be found?**
In Adopt good coding practices, (Optional) Eliminate repetitive code, Step 3.

**Describe the problem**
Well it's not necessarily a problem, but the code is not updated. To word it better, earlier in that page we were encouraged to remove the following text: (We don't use the variable roundUp anywhere else so just inline it into the if statement)

```
    val roundUp = binding.roundUpSwitch.isChecked
    if (roundUp) {
        tip = kotlin.math.ceil(tip)
    }
```

However in step 3, this code is re-introduced and may confuse the reader who would've already removed this and used the following as advised:
```
        if (binding.roundUpSwitch.isChecked) {
            tip = kotlin.math.ceil(tip)
        }
```

**Steps to reproduce?**
Nothing to reproduce, the information above is self explanatory. 

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 
Not a problem with android studio or API, but a problem with the documentation.

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @joel16,

Thank you for reaching out to us. The codelab instructions have been updated, so hopefully there won't be any more confusion.
![Screenshot 2023-03-31 at 4 18 13 PM](https://user-images.githubusercontent.com/86437155/229249031-84b14816-b8d3-434b-bfcd-a5df3c35482c.png)
