### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by charEric** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#24]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?return=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#4

**In which task and step of the codelab can this issue be found?**

Step 5, area of a circle

**Describe the problem**

You mention the area is 2 * PI * radius but then correct in the code block and say it's radius * radius * PI

See attached images
![Screen Shot 2020-10-30 at 3 27 12 PM](https://user-images.githubusercontent.com/4203842/97761963-73952b00-1ac4-11eb-9778-9c807d9c89b2.png)
![Screen Shot 2020-10-30 at 3 27 05 PM](https://user-images.githubusercontent.com/4203842/97761964-742dc180-1ac4-11eb-83e3-fd3c254028e8.png)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@charEric 
Thank you so much for reporting this issue. This is fixed and will be published soon.
