### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by gadikamerma** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#240]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#2

**In which task and step of the codelab can this issue be found?**
3. Vinculacion de vista(Im doing the coderlab in spanish)

**Describe the problem**
When put in MainActivity.kt the reference to the class "ActivityMainBinding" doing reference to "activity.XML" Android studio dont undertand the reference.

**Steps to reproduce?**
1. Go to MainActivity.kt
2. Copy and paste:
class MainActivity : AppCompatActivity() {

    lateinit var binding: ActivityMainBinding

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root)
    }
} 
And delete the predeterminate code
3. See error: Unresolved reference: ActivityMainBinding

**Versions**
_Android Studio version:_ 2020.1.3.24
_API version of the emulator:_ I dont know

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/40611917/142940407-a2cef3a8-9a4a-43cc-b2a6-3bb41f269e32.png)

**Comment by osuleymanova** [comment]
@gadikamerma 
Thank you for reaching out to us and providing the screenshot. It helped a lot! The error message may clarify what exactly should be fixed. In your case property 'binding' should be private. 
Please review the screenshot attached: there you may see the correct code `private lateinit var binding: ActivityMainBinding ` and the location of the emulator details in case if you need to provide them in your issue report next time:
![Screen Shot 2022-03-23 at 4 15 45 PM](https://user-images.githubusercontent.com/86437155/159813040-cd864be9-39ef-41e4-b561-e290a220a847.png)
Hope it helps!
