### ISSUE TITLE
Android Basics: change-app-theme

### ISSUE THREAD

**Issue by DiddiLeija** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#241]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-theme?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-change-app-theme#8

**In which task and step of the codelab can this issue be found?**

The last step (9).

**Describe the problem**

That step of the codelab provided a broken link: https://github.com/material-components/material-components-android-examples/blob/develop/MaterialThemeBuilder/README.md. It also makes a reference to https://github.com/material-components/material-components-android-examples/tree/develop/MaterialThemeBuilder, which does not exist now.

**Steps to reproduce?**

1. Go to the codelab.
2. Go to step 9.
3. Try to follow the steps. At some point, you should see a GitHub 404.

**Versions**

N/A

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@DiddiLeija 
Thank you for reaching out to us. 
As there are 8 slides only, no step 9, so we appreciate if you could provide the screenshot or more details how to reproduce the issue.

**Comment by DiddiLeija** [comment]
Well, the codelab has 9 steps for me:

![image](https://user-images.githubusercontent.com/83621221/143349816-ebe6fe88-c8c7-44be-8506-6103d34409c8.png)

(Google translated the codelab to spanish).

On that step, there are some instructions:

![image](https://user-images.githubusercontent.com/83621221/143351010-e8a71c5b-684e-4f01-a840-64f57da71c89.png)

It says that I have to go to https://github.com/material-components/material-components-android-examples, and open the `MaterialThemeBuilder` folder, which is not on the repo:

![image](https://user-images.githubusercontent.com/83621221/143353735-87e34c34-b281-4e98-88f3-794dd34a42b0.png)

The "provided URL" gives a GitHub 404:

![image](https://user-images.githubusercontent.com/83621221/143354351-9a193477-3c05-454f-9b60-e6a6f6be59a1.png)


Then, it suggested to follow the instructions from `MaterialThemeBuilder/README.md`:

![image](https://user-images.githubusercontent.com/83621221/143353465-0ef3b6dc-0a5c-4363-81ee-91c682bf2a30.png)

**Comment by DiddiLeija** [comment]
Hello, is there an update on this issue?

**Comment by osuleymanova** [comment]
@DiddiLeija 
Sorry for late reply. 
The issue that you presented to us is extremely important, and I thank you for bringing it to our attention. Actions from the localization team will soon be taken to fix it.

**Comment by DiddiLeija** [comment]
Oh, thanks @osuleymanova!
