### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by ElBrihento** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#246]
**URL of codelab**
The url of the codelab is:
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#4

**In which task and step of the codelab can this issue be found?**
Task n°5

**Describe the problem**
Where the text says "The floor area of a circular dwelling is PI * radius^2, or PI * radius * radius."
As far as I understood, radius^2 is not supported, unless an operator overload is implemented.
It would be better to keep only the second definition or explay the pow() function otherwise it may not be clear why the compilation (in the playground) gives the error "Unexpected tokens (use ';' to separate expressions on the same line).

I'm available for all questions.
Thank you for the help and awesome course!

**Comment by osuleymanova** [comment]
@ElBrihento 
Thank you for reaching out to us and sharing your concern. Our apologies that it caused any misunderstanding. The codelab content was updated:

![Screen Shot 2022-06-28 at 9 59 59 AM](https://user-images.githubusercontent.com/86437155/176241683-5160c945-6b8c-4950-aeb8-65eb0e2fdef8.png)
