### ISSUE TITLE
Android Basics issue: Function name mismatch in codelab

### ISSUE THREAD

**Issue by roozbeh1347** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#247]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests#3

**In which task and step of the codelab can this issue be found?**
Just before caption "Espresso" and after "4.Next, you need to write the test logic itself. ...":

> Create a function and call it calculate_20_percent_tip()

and code block:

```
@Test
fun calculate_20_percent_tip() {
}
```

**Describe the problem**
Name of the function here reads as "calculate_20_percent_tip", but at the rest of the doc it is referred to as "calculate_default_tip"

**Steps to reproduce?**
It's in the content. Just read the content as described.

**Versions**
_Android Studio version:_  N/A
_API version of the emulator:_  N/A

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/73668232/145694936-f534f66e-77b1-4fa8-8fa1-a67d5fa9dda8.png)
![image](https://user-images.githubusercontent.com/73668232/145694967-28832a96-3513-4797-b238-e44b999ddf82.png)

**Comment by osuleymanova** [comment]
@roozbeh1347 
Thank you for reaching out to us. The typo is fixed and will be published soon.
![Screen Shot 2022-03-28 at 5 02 42 PM](https://user-images.githubusercontent.com/86437155/160506836-4359a535-c611-484e-af15-e7f7aa8880fe.png)
