### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by Akshat0102** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#249]
**https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-instrumentation-tests**

**Writing Instrumentation Tests in getting user input in Android Basics Layout section**

**In the 4th part Write Your first instrumentation test, the 4th point says to create a function 'calculate_20_percent_tip()' but the actually created function is 'calculate_default_tip' as given in solution code below.**

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

![Screenshot (630)_LI](https://user-images.githubusercontent.com/76106653/145818870-79936578-7a90-437e-a6b9-bd884cb755f0.jpg)
![Screenshot (631)_LI](https://user-images.githubusercontent.com/76106653/145819048-d052fcd3-0d24-4d00-8d82-aec6b03425c2.jpg)

**Comment by osuleymanova** [comment]
@Akshat0102 
Thank you for reaching out to us. The issue is fixed and will be published soon.
![Screen Shot 2022-03-28 at 5 02 42 PM](https://user-images.githubusercontent.com/86437155/160660335-c3ef4845-0c0f-47a1-b15b-f0b5dfda2347.png)
