### ISSUE TITLE
Android Basics: change-app-icon

### ISSUE THREAD

**Issue by Zukka** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#25]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-icon?return=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-change-app-icon#2

**In which task and step of the codelab can this issue be found?**
3. Launcher Icons
Stap 4

**Describe the problem**
This is the current text:
For example, this is what res > mipmap-xxhdpi > ic_launcher_round.png looks like. Also notice the size of the asset is in the top right. This image is 192px x 192px in size.

Miss an **x** for res folder or change the size image to 144 x 144

**Comment by jtavva** [comment]
@Zukka 
Thank you so much for reporting this issue. This is fixed and will be published soon.
