### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by GPRSBirkbeck** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#250]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-instrumentation-tests#3

**In which task and step of the codelab can this issue be found?**
Task 4, step: Implement the Test function

**Describe the problem**
the user is asked to write test logic into the function titled: "calculate_default_tip().
However, the user is not asked to create this function, and no reference is made to it in the solution code here:
https://github.com/google-developer-training/android-basics-kotlin-tip-calculator-app-solution/blob/test_solution/app/src/androidTest/java/com/example/tiptime/CalculatorTests.kt

The user is asked to create a function titled calculate_20_percent_tip() instead.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@GPRSBirkbeck 
Thank you for reaching out to us. The issue is fixed and will be published soon.
![Screen Shot 2022-03-28 at 5 02 42 PM](https://user-images.githubusercontent.com/86437155/160660194-1290c01d-a8ec-412a-8b1c-96625e5d9911.png)
