### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by feldiaz** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#251]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-instrumentation-tests#3

**In which task and step of the codelab can this issue be found?**
FIRST ISSUE:
From:
@Test
fun calculate_20_percent_tip() {
}

to:
fun calculate_default_tip() {

SECOND ISSUE:
Actual test fails due to keyboard active while trying to reach the calculate and the final tip buttons.

**Describe the problem**
-Wrong functions name
-Code fails due to active keyboard.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**SOLUTION CODE:**
class CalculatorTests {
    @get:Rule
    val activity = ActivityScenarioRule(MainActivity::class.java)

    @Test
    fun calculate_default_tip(){

        onView(withId(R.id.cost_of_service_edit_text))
            .perform(typeText("50.00"))

        onView(withId(R.id.cost_of_service_edit_text)).perform(closeSoftKeyboard())

        onView(withId(R.id.calculate_button)).perform(click())

        onView(withId(R.id.tip_result))
            .check(matches(withText(containsString("10.00"))))
    }

}

**Comment by osuleymanova** [comment]
@feldiaz 
Thank you for reaching out to us. The issue is fixed and will be published soon.
![Screen Shot 2022-03-28 at 5 02 42 PM](https://user-images.githubusercontent.com/86437155/160659998-34d17fef-d358-4887-bdd2-f0ab85856d23.png)
