### ISSUE TITLE
Android Basics: polished-user-experience

### ISSUE THREAD

**Issue by renellebum** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#254]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-polished-user-experience#2

**In which task and step of the codelab can this issue be found?**
Polished User Experience
Step 3 Material Components

**Describe the problem**
Clicking a url brings user to the wrong Material Components page. Page needed is Switches but brings user to Checkboxes

**Steps to reproduce?**
1. Scroll down all the way until you see the section for "Switches"
2. Click on the url for the first "switch" link available in the first sentence.
3. See error that it takes you to to the Material Components Checkboxes page (https://material.io/components/checkboxes) instead of Switches

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![%pn_12_18_20_45_59](https://user-images.githubusercontent.com/86248849/146660697-557e2167-89bb-4e23-9625-cfca92a6934f.png)

**Comment by osuleymanova** [comment]
@renellebum 
The issue that you presented to us is extremely important, and I thank you for bringing it to our attention. The link is updated.
