### ISSUE TITLE
Android Basics issue: Running test case throws an exception

### ISSUE THREAD

**Issue by HtetLynnHtun** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#259]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-instrumentation-tests#3

**In which task and step of the codelab can this issue be found?**
Writing Your First Instrumentation Test

**Describe the problem**
In small screen device, running test case throws an exception:
Caused by: java.lang.RuntimeException: Action will not be performed because the target view does not match one or more of the following constraints:
(view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() covers at least <90> percent of the view's area)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
I googled the problem. I found the solution. The test function should scrollTo button first and then click button.
```
onView(withId(R.id.calculate_button))
            .perform(scrollTo(), click())
```
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@HtetLynnHtun 
Thank you for reaching out to us. We are happy that your issue was resolved.
