### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by Bozhko-Pavel** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#26]
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?return=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%3Fhl%3Den%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator&hl=en#3

almost at the very end, when you need to start the application for testing, a piece of code does not work: "binding.tipResult.text = getString (R.string.tip_amount, formattedTip)"

I did everything according to the instructions. The moment has come for testing the application. I started it all worked, entered the text into the "EditText" and clicked "Calculate", but some of the code did not work correctly. I had to replace this code: "binding.tipResult.text = getString (R.string.tip_amount, formattedTip)" like this: "binding.tipResult.text = getString (R.string.tip_result_text) +" "+ formattedTip" and it worked correctly.

![Безымянный](https://user-images.githubusercontent.com/73753512/97785099-310b4580-1bcd-11eb-9beb-773a4625c0e9.jpg)

**Steps to reproduce?**
1. launch and debug
2. Click on Calculate
3. the compiler gives no errors

**Versions**
_Android Studio version:_ 4.0.2
_API version of the emulator:_ I don't know where to look at it :(

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@Bozhko-Pavel 
Thank you for reaching out to us. 

I think you missed the following step:

Open strings.xml (**app > res > values > strings.xml**)
Change the `tip_amount` string from Tip Amount to Tip Amount: `%s`.
`<string name="tip_amount">Tip Amount: %s</string>
`
Once you fix this, the code in the codelab should work without any changes.

**Comment by jtavva** [comment]
Hope the above comment resolved your issue. 
It's been 14 days since we've heard from you, so we are going to close this issue.
You can always reopen this ticket or raise a new one if you need any further assistance.
