### ISSUE TITLE
Android Basics: classes-and-inheritance (RoundHut re-declaration of 'residents' member)

### ISSUE THREAD

**Issue by MitchelCarreon** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#262]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#5

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
As suggested in [Task 4](https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#3),  the intent was to reuse the superclass' (i.e. _Dwelling_) properties. However, as depicted in [Task 5](https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#4) and in the [Solution Code](https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#5), the member _residents_ is re-declared using _val_ in the _RoundHut_ subclass.

**Steps to reproduce?**
1. Go to... [Solution Code](https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#5)
2. Scroll down to the class declaration for _RoundHut_
3. The code still runs. But [Task 4 ](https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#3)explicitly mentioned not to re-declare _residents_

**Versions**
_Android Studio version:_ N/A
_API version of the emulator:_ N/A

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@MitchelCarreon 
Thank you for reaching out to us. The typo is fixed and will be published soon:

![Screen Shot 2022-06-27 at 5 07 40 PM](https://user-images.githubusercontent.com/86437155/176059823-9b1d7322-a812-4253-9103-e5798ba71edb.png)
