### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by SaiMadhavanG** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#263]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-instrumentation-tests#3

**In which task and step of the codelab can this issue be found?**
Step 4. of "Writing your first Instrumentation test" and "Implement the test function"

**Describe the problem**
Mismatch of function name in it's definition. While Step 4. creates a function named "calculate_20_percent_tip", the other steps are 
working with the function named "calculate_default_tip"

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
<img width="585" alt="image" src="https://user-images.githubusercontent.com/64302531/147540623-cddad41f-5204-4539-a2f8-e967aefe88ff.png">
<img width="586" alt="image" src="https://user-images.githubusercontent.com/64302531/147540684-3bbc8292-7408-40c3-a5d5-e81f1272e452.png">

**Comment by osuleymanova** [comment]
@SaiMadhavanG 
Thank you for reaching out to us. The typo is fixed and will be published soon.
![Screen Shot 2022-03-30 at 3 42 10 PM](https://user-images.githubusercontent.com/86437155/160942906-9edfae42-d3a7-431f-9667-4b3274919c79.png)

![Screen Shot 2022-03-30 at 3 41 41 PM](https://user-images.githubusercontent.com/86437155/160942922-ef801615-206d-4bc9-8bed-8fa655139d95.png)
