### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by chintanjethi** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#264]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-instrumentation-tests

**In which task and step of the codelab can this issue be found?**
Writing Your First Instrumentations Test

**Describe the problem**
In step 4 we told to define function named calculate twenty percent tip and then in implement the test function step we are told to get to calculate default tip function which is never created hope you fix that i got confused for 20 mins searching for calculate default tip function in whole program

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@chintanjethi 
Thank you for reaching out to us and reporting this typo. The codelab content is updated and will be published soon.
![Screen Shot 2022-03-30 at 3 39 03 PM](https://user-images.githubusercontent.com/86437155/160942599-0aba59ac-359e-450d-b73d-25e55cb736b9.png)

**Comment by osuleymanova** [comment]
Duplicate of #263
