### ISSUE TITLE
Android Basics issue: Code missing a line break renders unusable

### ISSUE THREAD

**Issue by outloudvi** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#265]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests

**In which task and step of the codelab can this issue be found?**
4. Writing Your First Instrumentation Test

**Describe the problem**
A line break is missing, giving:

``` kotlin
@get:Ruleval activity = ActivityScenarioRule(MainActivity::class.java)
```

It probably should be:

``` kotlin
@get:Rule
val activity = ActivityScenarioRule(MainActivity::class.java)
```

**Steps to reproduce?**
1. Go to the link above
2. Click "4 Writing Your First Instrumentation Test" at left

**Versions**
* Android Studio version: Unrelated
* API version of the emulator: Unrelated

**Additional information**
![The website screenshot.](https://user-images.githubusercontent.com/19144373/147725257-0ab6d934-0689-4358-ab11-d369500d73fa.png)

**Comment by osuleymanova** [comment]
@outloudvi 
Thank you for reaching out to us. The issue is fixed and republished.
