### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by charEric** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#27]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?return=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#2

**In which task and step of the codelab can this issue be found?**

Enable View Binding

**Describe the problem**

I was receiving an error and [realized it's because I'm not running AS 4.0+](https://stackoverflow.com/questions/58692811/error-when-adding-buildfeatures-in-build-gradle-file). You may want to add a note about this issue for versions sub 4

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by charEric** [comment]
Actually looks like I had to change it to: 

`
viewBinding {
        enabled = true
    }
`
https://stackoverflow.com/questions/57947991/error-could-not-find-method-viewbinding-for-arguments

**Comment by charEric** [comment]
OK, I actually had to do quite a bit to get the app to build: 

- update AS
- update gradle
- change the code (mentioned in previous comment)
- import `com.elinnert.tiptime.databinding.ActivityMainBinding` to MainActivity

FYI

**Comment by jtavva** [comment]
@charEric 
Thanks for reporting, we recommend that you use the latest version of Android Studio for this course. 
Regularly check and update the Android Studio version.
