### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by AlejoRMinetti** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#279]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#3

**In which task and step of the codelab can this issue be found?**

The output of the code:

val roundHut = RoundHut(3)

with(roundHut) {
    println("\nRound Hut\n=========")
    println("Material: ${buildingMaterial}")
    println("Capacity: ${capacity}")
    println("Has room? ${hasRoom()}")
}

Is shown as:
Round Hut
=========
Material: Straw
Capacity: 4
Has room? true

**Describe the problem**

This output should be:
Round Hut
=========
Material: Straw
Capacity: 3
Has room? false

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

Its simple enough to be resolved with no more details.
Thanks to the Google Team for this free and nice course!
Bye!

**Comment by osuleymanova** [comment]
@AlejoRMinetti 
Thank you for reaching out to us. In RoundHut with 3 residents and capacity set to 4 the code output provided in the codelab is correct:

![Screen Shot 2022-06-27 at 4 54 19 PM](https://user-images.githubusercontent.com/86437155/176058700-c3cba67b-a385-4fc7-8214-8e10fd9fca4b.png)
