### ISSUE TITLE
Android Basics: Done/Next button is missing xml-layouts

### ISSUE THREAD

**Issue by nrickosta** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#28]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts?return=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-xml-layouts#10

**In which task and step of the codelab can this issue be found?**
11. Practice on your own

**Describe the problem**
At the End there is no DONE button. I've tried to do it with other browser and none was able to show me the button (chrome & firefox), in Fedora 32

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/73033415/98257698-e6484f80-1f77-11eb-8112-17e61265ec9b.png)

**Comment by osuleymanova** [comment]
@nrickosta 
Thank you for reporting this issue. It was fixed and published: 

https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-xml-layouts#10
