### ISSUE TITLE
Android Basics issue: Error in function name in Write Instrumentation Tests Colab

### ISSUE THREAD

**Issue by ingdicath** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#280]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-instrumentation-tests#3

**In which task and step of the codelab can this issue be found?**

Task: 4. Writing Your First Instrumentation Test

Step: 4. Next, you need to write the test logic itself. Create a function and call it `calculate_20_percent_tip() `and annotate it with the @Test annotation.

<br>**Describe the problem**

Colab says: "Create a function and call it `calculate_20_percent_tip()`", however, in the **Implement the Test function** section and in the **solution code** you will never see this name, instead you see the function name `calculate_default_tip()`

```
@Test
   fun calculate_default_tip() {
       onView(withId(R.id.cost_of_service_edit_text))
           .perform(typeText("50.00"))
   ...
}
```

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

I consider the correct function name is `calculate_default_tip()`. It is just an error in the function name.

**Comment by ShahsTestingZone** [comment]
Hi See my response. 

But you need to use clostSoftKeyboard() after typing text. 

   @Test
    fun calculate_20_percent_tip() {

        onView(withId(R.id.cost_of_service_edit_text))
            .perform(typeText("50.00"))

        closeSoftKeyboard()

        onView(withId(R.id.calculate_button))
            .perform(click())

        onView(withId(R.id.tip_result))
            .check(matches(withText(containsString("Tip Amount: £10.00"))))
    }

**Comment by osuleymanova** [comment]
@ingdicath 
Thank you for reaching out to us. The typo  is fixed and will be published soon.
![Screen Shot 2022-03-28 at 5 02 42 PM](https://user-images.githubusercontent.com/86437155/160652095-f28a7fdf-37ba-44ab-b566-55e5c6339c6e.png)
