### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by SamuelWakoli** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#284]
**URL of codelab**: https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#5

**In which task and step of the codelab can this issue be found?**: The solution code

**Describe the problem**:
I have copy pasted the following:
fun main() {
   val squareCabin = SquareCabin(6, 50.0)
   val roundHut = RoundHut(3, 10.0)
   val roundTower = RoundTower(4, 15.5)

   with(squareCabin) {
       println("\nSquare Cabin\n============")
       println("Capacity: ${capacity}")
       println("Material: ${buildingMaterial}")
       println("Floor area: ${floorArea()}")
   }

   with(roundHut) {
       println("\nRound Hut\n=========")
       println("Material: ${buildingMaterial}")
       println("Capacity: ${capacity}")
       println("Floor area: ${floorArea()}")
       println("Has room? ${hasRoom()}")
       getRoom()
       println("Has room? ${hasRoom()}")
       getRoom()
       println("Carpet size: ${calculateMaxCarpetSize()}")
   }

   with(roundTower) {
       println("\nRound Tower\n==========")
       println("Material: ${buildingMaterial}")
       println("Capacity: ${capacity}")
       println("Floor area: ${floorArea()}")
       println("Carpet size: ${calculateMaxCarpetSize()}")
   }
}

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...
Repetition of the println("Has room? ${hasRoom()}") 

![issue](https://user-images.githubusercontent.com/97802502/149632239-45cb9bf3-cb9d-47b0-928e-2a3e2a38f37b.png)

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@SamuelWakoli 
Thank you for reaching out to us. There is no typo in the Solution code as those steps were implemented earlier:

![Screen Shot 2022-09-13 at 4 04 43 PM](https://user-images.githubusercontent.com/86437155/190025177-9866adec-8b8a-4557-b04b-edcccd00bac8.png)

Happy coding!
