### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by TomsCodeVault** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#286]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-instrumentation-tests#3

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
No real problem just two corrections.

1. Under:  "Implement the Test function" it says:

"Now, in the **calculate_default_tip()** function in your test class, you can write the test logic."

Should be: "Now, in the **calculate_20_percent_tip()** function in your test class, you can write the test logic."

2. In the following code snippet:

onView(withId(R.id.tip_result))
    .check(matches(withText(containsString("$10.00"))))

There is a "$" in the containsString string argument. Later in the document the argument is shown without the dollar sign. This doesn't matter to the functioning of the test but it's inconsistent and potentially confusing to a beginner like me.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by v2-kaj** [comment]
I saw this too. The method name needs to be changed so that it is consistent. I got confused for a moment.

**Comment by osuleymanova** [comment]
@TomsCodeVault 
Thank you for reaching out to us. The typo is fixed and will be published soon.
![Screen Shot 2022-03-28 at 5 02 42 PM](https://user-images.githubusercontent.com/86437155/160508889-598fed96-e94d-4843-bcbe-23496daba890.png)
