### ISSUE TITLE
Android Basics: change-app-theme

### ISSUE THREAD

**Issue by scorelocity** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#290]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-theme#2

**In which task and step of the codelab can this issue be found?**
10

**Describe the problem**
The default color of the button is purple with white text, not grey with black text as the picture indicates.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 2020.3.1 Patch 4
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@scorelocity 
Thank you for reaching out to us. The image is updated and will be published soon.
