### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by Anton-Lyskavets** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#291]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
TRAINING
ANDROID BASICS IN KOTLIN
LAYOUTS
USER INPUT 2 (Get user input in an app: Part 2)
Write Instrumentation Tests
4. Writing Your First Instrumentation Test

**Describe the problem**

when running the test, the keyboard appeared
can hide part of the screen (depends on the emulator). And the button can't be pressed to calculate the tip. And I didn't pass the test. Solution to the problem: add before click() - scrollTo()
What would happen: 
        onView(withId(R.id.calculate_button))
            .perform(scrollTo(), click()) 
I suggest you add this to your tutorial. 
Thanks =) 

**Steps to reproduce?**
described above 

**Versions**
_Android Studio version:_ bumblebee 2021.1.1
_API version of the emulator:_ Pixel XL (API 30)

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @Anton-Lyskavets,

Thank you for reaching out to us and sharing your feedback.
