### ISSUE TITLE
Unresolved reference: espresso in codelab Write Instrumentation Tests

### ISSUE THREAD

**Issue by FerdinandoCavaliere** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#292]
[**URL of codelab**](https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-instrumentation-tests#3)

4 (Write Instrumentation Tests)

I am using the Tip Time app created in previous codelabs. When I run the test described in this codelab "Write Instrumentation Tests" android studio compiles the app but when I try to run it in the emulator it reports Unresolved reference: expressed

**Versions**
_Android Studio version: 2021.1.1 Bumblebee

dependencies {
    implementation 'androidx.core:core-ktx:1.7.0'
    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'com.google.android.material:material:1.5.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.3'
    implementation 'androidx.test.ext:junit-ktx:1.1.3'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
}

**Comment by schordas** [comment]
I'm unable to reproduce this. Can you provide more information on how you are trying to run the test and what your test code looks like?

**Comment by osuleymanova** [comment]
@FerdinandoCavaliere 
Please provide the requested by @schordas information to proceed further. Unfortunately the issue will be closed within 7 days if there is no further update.
