### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by dimd11** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#295]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#6
**In which task and step of the codelab can this issue be found?**

**Describe the problem**

At chapter 7. Summary says that you have learned how to use the "super" keyword to reference functions and properties in the parent class. The keyword super in not reference  to any part of the class and inheritance session.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@dimd11 
Thank you for reaching out to us. Following the steps provided in the codelab you will find all the information about class hierarchy including about superclass.
