### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by NikolozMiruashvili** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#297]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-instrumentation-tests#3

**In which task and step of the codelab can this issue be found?**
4

**Describe the problem**
 a small spelling mistake. 
"and let's you interact with UI components through code."
should be: "and lets you interact with UI components through code."

**Steps to reproduce?**
read the codelab

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@NikolozMiruashvili 
Thank you for reaching out to us. The typo is fixed and will be published soon.
