### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by AshutoshSahni** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#3]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance#4

**In which task and step of the codelab can this issue be found?**
Under the Heading "Implement floorArea() for RoundHut, Line three, which says, "The floor area...."

**Describe the problem**
The formula written is 2*PI*radius, but here we are calculating area so it should be PI*radius*radius.
It's correct in the code but statement is wrong. So it might mislead someone.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by GeneAndGoogle** [comment]
Thank you and the others for the report. This has been fixed and will be re-published soon.

**Comment by jtavva** [comment]
As mentioned this fix will be published soon. Closing for now
