### ISSUE TITLE
Android Basics: xml-layouts

### ISSUE THREAD

**Issue by OlafusS5** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#302]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-xml-layouts#3

**In which task and step of the codelab can this issue be found?**

Add cost of service text field

Build the layout in XML

**Describe the problem**

Sentence before code:
Nice job! It doesn't do much yet, but you've got a good start and have edited some XML. The XML for your layout should look something like this.

android:padding="16dp" is added

Sentence before code:
At this point, your XML should look like this.

android:padding="16dp" is missing in final code with no clue for deleting it

**Steps to reproduce?**
1. Go to URL and find padding
2. Click on the latest appearance 
3. See error in the final code appearance is missing 

**Versions**
_Android Studio version:_  website study materials
_API version of the emulator:_ website study materials 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@OlafusS5 
The issue that you presented to us is important, and I thank you for bringing it to our attention. Actions are taken to fix it:
![Screen Shot 2022-03-23 at 4 49 51 PM](https://user-images.githubusercontent.com/86437155/159814916-6480f7de-2ccd-4f63-aebc-6a19f72bdc59.png)
