### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by kennethchanchifung** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#303]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-instrumentation-tests#3

**In which task and step of the codelab can this issue be found?**
Title: 
Espresso

Content:
First, you need to write code to enter the bill amount in the Cost of Service input text view. Navigating to app -> src -> main -> res -> activity_main.xml indicates that the ID of the TextInputEditText is cost_of_service_edit_text. Copy the ID name, which we will need later for the test.

**Describe the problem**
Instead of 
"Navigating to app -> src -> main -> res -> activity_main.xml"

Should be
"Navigating to app -> src -> main -> res -> **_layout_** -> activity_main.xml"

**Steps to reproduce?**

**Versions**

**Additional information**

**Comment by osuleymanova** [comment]
@kennethchanchifung 
Thank you for reaching out to us. The path is updated and will be published soon.
