### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by martinezm2049** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#304]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-instrumentation-tests#3

**In which task and step of the codelab can this issue be found?**
"Implement the Test function section", Step 2.

**Describe the problem**

Codelab says "...and so the id name that is passed to the withText() function...". The correct function is withId(), not withText().

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @zjensen1022,

Thank you for reaching out to us and reporting this typo. It is fixed:

![Screenshot 2023-03-31 at 3 31 44 PM](https://user-images.githubusercontent.com/86437155/229249757-ec4168cf-7125-49dd-af35-a40dfd13fabe.png)
