### ISSUE TITLE
Android Basics issue: Typo on page

### ISSUE THREAD

**Issue by skatingtamara** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#306]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%3Fhl%3Den%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-instrumentation-tests&hl=en#3

**In which task and step of the codelab can this issue be found?**
Step 4. Writing Your First Instrumentation Test

**Describe the problem**
Initially the codelab asks us to create a function called "calculate_20_percent_tip()". Then in the next step, we are asked to use the function "calculate_default_tip()" It seems we could use the later.

Initially:
![image](https://user-images.githubusercontent.com/98510821/154891408-ccd12bd5-15ff-4879-8d0a-bca2601ba228.png)

Then:
![image](https://user-images.githubusercontent.com/98510821/154891457-2d14e4c1-8ed4-411f-aa29-1fe3d4240280.png)

**Comment by osuleymanova** [comment]
@skatingtamara 
Thank you for reaching out to us. The issue is fixed and will be published soon.
![Screen Shot 2022-03-24 at 2 51 26 PM](https://user-images.githubusercontent.com/86437155/160016418-c223f38e-2685-4cab-a061-c20840133c86.png)
