### ISSUE TITLE
Android Basics issue: Unable to find instrumentation test solution code

### ISSUE THREAD

**Issue by skatingtamara** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#307]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%3Fhl%3Den%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-instrumentation-tests&hl=en#5

**Describe the problem**
The solution code for the Instrumentation Test codelab only links to the original tip calculator solution, which does not have the test file created in the codelab. Additionally, the codelab states the solution code is in the module "test_solution" but I could not find that in the linked code.

**Additional information**
![image](https://user-images.githubusercontent.com/98510821/154896473-36c416c3-6e62-44e1-bcaa-cd94cc335161.png)

**Comment by osuleymanova** [comment]
@skatingtamara 
Thank you for reaching out to us. Please see the screenshot attached.
![Screen Shot 2022-03-25 at 5 03 20 PM](https://user-images.githubusercontent.com/86437155/160216288-3b3d18ea-830a-486f-983d-a3815d616060.png)
Hope it helps.

**Comment by tamarabuilds** [comment]
@osuleymanova Thanks! Newbie here. I'm getting the hang of it now :)

**Comment by osuleymanova** [comment]
@skatingtamara 
No problem! You are most welcome to address any concern to us.
