### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by heroddaji** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#311]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-instrumentation-tests#3

**In which task and step of the codelab can this issue be found?**
Task 4: Writing your first instrument test

**Describe the problem**
The Instrument test crash on my emulator.
I need to hide the softKeyboard before clicking the button

Here is my solution:

onView(withId(R.id.cost_of_service_edit_text)).perform(typeText("50.00"))

onView(withId(R.id.cost_of_service_edit_text)).perform(ViewActions.closeSoftKeyboard())

onView(withId(R.id.calculate_button)).perform(click())

onView(withId(R.id.tip_result)).check(matches(withText(containsString("$10.00"))))

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by Hebelag** [comment]
Ah darn I wrote an issue about that a couple of minutes ago. An easier solution is to append "\n" after "50.00"
So you have **onView(withId(R.id.cost_of_service_edit_text)).perform(typeText("50.00\n"))**
The newline emulates an ENTER key event, so the soft keyboard closes itself.
