### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by Lunarclipper** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#314]
Hello,

This is not an error, more of a suggestion to help make learning easier. You don't have a way to make such a suggestion, so I am placing it here. I am sorry if this causes any trouble:

So let's say I am working my way through Android Basics in Kotlin on my own (which I am). I come to a code lab, read through its prerequisites, and find a concept I feel a little shaky on for some reason. The prerequisite lists the concept I should be familiar with, great, but does not tell me where this was taught. This means, if I don't remember, I have to go searching through the codelabs I have worked through until I find it. It would be great if the prerequisite didn't just list the concept we need to know to proceed with the codelab, but also had a link to the codelab where the concept was taught.

for example:
in Android Basics in Kotlin > Unit 2: Layouts > Pathway 1  Get user input in an app: Part 1 > Classes and inheritance in Kotlin, under prerequisites, where it says, "Able to define a class in Kotlin, create an object instance from it, and access its properties and methods.", there would be a link at the end to  Android Basics in Kotlin > Unit 1: Kotlin basics > Classes and object instances in Kotlin. This would allow those of us who feel shaky on the information presented in "Classes and inheritance in Kotlin" for any reason (like maybe life stepped up and demanded our attention elsewhere, so it has been a while since we did that codelab) to brush up on the concept quickly, without having to spend a lot of extra time searching for it. Not all prerequisites are so easy to find, some of them are down inside a codelab not named for the concept we are searching for. 

I hope this is a suggestion that will work, as it will make it easier for those of us trying to teach ourselves around the hectic demands of life.  Thank you for your time.  All the best to you and yours,
Alan
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by Hebelag** [comment]
Yes I agree on that one. I did a course on Kotlin before starting with Android Basics. Check out **JetBrains Academy: Kotlin Basics** which really helped me learn Kotlin in more or less a month:  [Kotlin Basics](https://hyperskill.org/tracks/18)
