### ISSUE TITLE
Android Basics: change-app-theme

### ISSUE THREAD

**Issue by hipjoiner** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#316]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-theme?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-change-app-theme#2

**In which task and step of the codelab can this issue be found?**
First run of the new Empty Activity for this codelab.

**Describe the problem**
"Button" is purple, not grey.  Image of program run shows button in grey, and remark afterward says, "We will change the button's color to the color of the theme's primary color in future steps."  But for my first run (physical Samsung SM-T870 running API level 31), the button is purple, which I assume to be the theme's primary color.  So different from image, and presumably already changed.

**Steps to reproduce?**
See "Describe" above.  Just follow codelab steps, and first run yields a result different from image shown in codelab.  I copied and pasted all XML provided, as instructed.

**Versions**
_Android Studio version:_ 2021.1.1 Patch 2
_API version of the emulator:_  Not an emulator, physical device: Samsung  SM-T870 tablet, running API level 31

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._  "Button" is purple, not grey.

**Comment by Hebelag** [comment]
Yes that is true. It is an old version of the code I guess. The view that should be written in the layout file should be **androidx.appcompat.widget.AppCompatButton** and not the standard **Button**.

**Comment by osuleymanova** [comment]
@hipjoiner 
Thank you for reaching out to us. The image is updated and will be published soon.
