### ISSUE TITLE
Android Basics issue: First Instrumentation Test needs an update

### ISSUE THREAD

**Issue by kyooryoo** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#319]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-instrumentation-tests#3

**In which task and step of the codelab can this issue be found?**
[4. Writing Your First Instrumentation Test](https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-instrumentation-tests#3)

**Describe the problem**
After entering the service fee, soft keyboard is overlaying on the Calculate Button and makes it unavailable to click.
This issue only happen on virtual or physical device with a small sized screen.

The solution is adding `.perform(ViewActions.closeSoftKeyboard())` to turn off soft keyboard after interring price.
```
        onView(withId(R.id.cost_of_service_edit_text))
            .perform(typeText("50.00"))
            .perform(ViewActions.closeSoftKeyboard())
```

**Steps to reproduce?**
1. Change virtual or physical device to someone with a small screen
2. Run the test
3. See error:
*androidx.test.espresso.PerformException: Error performing 'single click' on view 'view.getId() is <2131230820/com.example.tiptime:id/calculate_button>'.*
*Caused by: java.lang.RuntimeException: Action will not be performed because the target view does not match one or more of the following constraints:
(view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() covers at least <90> percent of the view's area)*

**Versions**
_Android Studio version:_ Android Studio Bumblebee | 2021.1.1 Patch 1
_API version of the emulator:_  32

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
<img width="1434" alt="截屏2022-03-11 上午8 27 47" src="https://user-images.githubusercontent.com/16432725/157778294-f75da571-b320-47f2-b9ea-8e5d3e05e933.png">

**Comment by osuleymanova** [comment]
@kyooryoo 
Thank you for reaching out to us and suggesting the solution. The content is updated and will be published soon
![Screen Shot 2022-03-30 at 3 05 36 PM](https://user-images.githubusercontent.com/86437155/160938876-8d589ec6-0480-4582-b437-594d2bfb1265.png)
.
