### ISSUE TITLE
Android Basics: change-app-theme

### ISSUE THREAD

**Issue by charEric** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#32]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-theme?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-change-app-theme#2

**In which task and step of the codelab can this issue be found?**

Step 3: Themes | Separate Styles from Themes

**Describe the problem**

> You do not need to do the steps in this section if you are using Android 4.1 or later

Not an issue but an interesting point. I updated my AS with my TipTime project already created and though I'm on AS 4.1, my themes.xml didn't appear because when I created the project I was on 3.6. 

You may want to mention this in case other users update midway, though I also recognize this is probably an edge case 🤷‍♂️

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@charEric 

 In [Change the app theme](https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-theme?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-change-app-theme#2) codelab, in task **3. Themes**, in the section  **Separate Styles from Themes**, the instructions to create themes files is given (if you are not using AS4.0).

Thank you for reaching out to us.
