### ISSUE TITLE
Android Basics issue: typo in steps content

### ISSUE THREAD

**Issue by khmaies5** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#320]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-instrumentation-tests#3

**In which task and step of the codelab can this issue be found?**
In implement the test function task

**Describe the problem**
in the previous task is states that you should create a function called "calculate_20_percent_tip"
but in the next step it's saying "Now, in the calculate_default_tip() function in your test class..." the function name should be the same in both steps

**Comment by osuleymanova** [comment]
@ @khmaies5 
Thank you for bringing this issue to our attention. Actions are taken to fix and republish it soon.
