### ISSUE TITLE
Android Basics: xml-layouts

### ISSUE THREAD

**Issue by NikoLewis** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#325]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-xml-layouts#6

**In which task and step of the codelab can this issue be found?**
Unit 2 >  Pathway 1 > Activity 4 Create XML layouts for Android > Step 7

**Describe the problem**

The provided path to navigate to all string resources in project view  is incorrect. 
`Open app > res > values > strings.xml`

It should be:
 `Open app > src > main > res > values > strings.xml`

**Steps to reproduce?**
1. Go [Unit 2 >  Pathway 1 > Activity 4 Create XML layouts for Android > Step 7](https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-xml-layouts#6)
2. Click on...  Take Codelab >  scroll to step 7
4. See 
Incorrect path provided in instructions `Open app > res > values > strings.xml`

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

n/a

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

![screenshot](https://user-images.githubusercontent.com/20360382/159179627-6667081e-046c-49fd-bf62-e1afb0f43b60.png)

**Comment by osuleymanova** [comment]
@NikoLewis 
Thank you for reaching out to us. 
The path provided in the codelab is correct. The attachment is for your reference:
![Screen Shot 2022-03-23 at 2 48 53 PM](https://user-images.githubusercontent.com/86437155/159802215-c0613fee-ce57-4021-b3dd-faea4eab73f5.png)
As no further actions required the issue is closed.
