### ISSUE TITLE
Android Basics: polished-user-experience

### ISSUE THREAD

**Issue by Lunarclipper** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#328]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-polished-user-experience?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-polished-user-experience#5

**In which task and step of the codelab can this issue be found?**
Create a more polished user experience, Hide keyboard on Enter key, step 2

**Describe the problem**

```
binding.costOfServiceEditText.setOnKeyListener { view, keyCode, _ -> handleKeyEvent(view, keyCode)
   }
```
Entering the above code, or even copying and pasting it into my app directly from the codelab flags 'costOfServiceEditText', and by extention the 'view' and 'keyCode' right after the curly braces (but strangely not the 'view' and 'keyCode' after 'handlerKeyEvent'). costOfServiceEditText is flagged with "Unresolved reference", while view and keyCode are flagged with "Cannot infer a type for this parameter. Please specify it explicitly."

**Steps to reproduce?**
Enter the code as presented in the codelab

**Versions**
_Android Studio version:_ Bubmblebee 2021.1.1 Patch 2, running on Ubuntu Linux
_API version of the emulator:_ 

**Additional information**
Hovering over the issue, then selecting "Rename reference" from the pop up, and "costOfService", thereby dropping "EditText", fixes the problem and the program builds and runs as expected.
![codelab_issue_24Mar2022](https://user-images.githubusercontent.com/94221018/159870754-5dab9b4a-85b9-433f-aa1c-3d9e9235b462.png)

After fixing this issue in the above manner I can bring back the errors and remove them again by simply pressing CTRL-Z and SHIFT-CTRL-Z. This indicates to me the codelab has a typo in the reference.

_Include screenshots if they would be useful in clarifying the problem._

**Comment by JSwtbap** [comment]
I got no errors, but the keyboard does NOT go away when I run the app.  I also tried it on costOfService and on calculateButton, got no errors, but the keyboard just doesn't go away.

**Comment by JSwtbap** [comment]
Oh, my mistake. The keyboard does go away if I hit ENTER. It doesn't go away when I hit the CALCULATE button.
