### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by Daravolo** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#33]
Classes and inheritance in Kotlin
5. Modify classes in the hierarchy
Implement floorArea() for RoundHut

(...)
**The floor area of a circular dwelling is 2 * PI * radius.**
(...)

area is wrong: instead 2 * PI * radius, is PI * radius * radius

**Comment by jtavva** [comment]
@Daravolo 
Thank you for reporting.
This issue be fixed now.
