### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by RFProgrammer** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#331]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-instrumentation-tests#3

**In which task and step of the codelab can this issue be found?**
Write Instrumentation Tests --> Task 4 --> Implement the Test function --> 1

**Describe the problem**
First, in this codelab creates a function with the following name: "calculate_20_percent_tip()". And then, it calls it as "calculate_default_tip()".

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@RFProgrammer 
Thank you for reaching out to us. Could you share the screenshot or the code snippet where "calculate_default_tip()" is used?

**Comment by osuleymanova** [comment]
Closing this issue, since there is no reply.
Please create a new one, if you need help.
All the best learning Android.
