### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by Tinribs507** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#339]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#4

**In which task and step of the codelab can this issue be found?**

Task 5 (Modify Classes in the [hierarchy]

Implement floorArea() for RoundHut

**Describe the problem**

In the code snippet it it says:

open class RoundHut(
   **val residents: Int,** 
   val radius: Double) : Dwelling(residents) {

this should be:

open class RoundHut(
   **residents: Int,** 
   val radius: Double) : Dwelling(residents) {

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@Tinribs507 
Thank you for reaching out to us. The typo is fixed and will be published soon:


![Screen Shot 2022-06-27 at 4 08 56 PM](https://user-images.githubusercontent.com/86437155/176051673-8e59de3e-642d-44db-ad7b-9b407b5fb77a.png)
