### ISSUE TITLE
Android Basics: xml-layouts

### ISSUE THREAD

**Issue by Daravolo** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#34]
at https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-xml-layouts#5

-> Create XML layouts for Android -> 6. Complete the rest of the layout ->

>**You want the Switch to be as wide as the parent, so you might think the width should be set to match_parent. As noted earlier, you can't set match_parent on UI elements in a ConstraintLayout**

info out-dated: is possible use match_parent in switches and buttons at least

**Comment by jtavva** [comment]
@Daravolo 
Thank you for reporting!
For any child views(including button and switches) inside the constraint layout, the constraint you can set is  0dp(match_constraint).

**Comment by Daravolo** [comment]
Yeah, but _"noted earlier, you can't set match_parent on UI elements in a ConstraintLayout"_ is untrue, because you can set android:layout_width="match_parent" in switch and button as well, actually works.

**Comment by jtavva** [comment]
@Daravolo 
It is not a recommended practice to use match_parent in this case.

> Important: MATCH_PARENT is not recommended for widgets contained in a ConstraintLayout. Similar behavior can be defined by using MATCH_CONSTRAINT with the corresponding left/right or top/bottom constraints being set to "parent".

For more information please refer: 
https://developer.android.com/reference/androidx/constraintlayout/widget/ConstraintLayout#developer-guide
