### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by sufood** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#340]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#2

**In which task and step of the codelab can this issue be found?**
Enable view binding

**Describe the problem**
Enabling viewBinding seems to default to Groovy syntax as per
https://stackoverflow.com/questions/68569379/access-to-viewbinding-exceeds-its-access-rights

I had to remove the "=" to get the codelab to work
eg:

_buildFeatures {
    viewBinding true
}_

**Steps to reproduce?**
Follow steps in codelab and ActivityMainBinding will remain undefined in MainActivity.kt until the gradle syntax is corrected as per above

**Versions**
_Android Studio version:_ 
Android Studio Bumblebee | 2021.1.1 Patch 3
Build #AI-211.7628.21.2111.8309675, built on March 17, 2022
Runtime version: 11.0.11+0-b60-7590822 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: external.system.auto.import.disabled=true

_API version of the emulator:_ 
API 31

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@sufood 
Thank you for reaching out to us and sharing your experience.
