### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by smy5152** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#342]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#2

### NEWBIE SOLUTION STEPS

**In which task and step of the codelab can this issue be found?**
_2. Replace all of the existing code for MainActivity class with this code to setup the MainActivity to use view binding:_

**Describe the problem**
Unresolved reference: ActivityMainBinding
Dependencies & code references to research and solves various imports/includes etc should be provided as links.
I had to do the below to resolve it...

1. Enclose activity_main.xml with `<layout> <androidx... </androidx... </layout>`
2. Add in build.gradle under android ` buildFeatures {         dataBinding = true        viewBinding = true    }    ` 
3. IMPORT ` import com.example.<package_name>.databinding.ActivityMainBinding `
4. PLUGINS ` id 'kotlin-kapt' ` in build.gradle (Module :app)
5. Finally Clean, Build.

**Steps to reproduce?**
1. Go to... You android studio
5. Click on... MainActivity.kt, copy-paste the sample code on the link above to use ViewBinding.
6. See error... Build failed - cannot resolve / import dependencies

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

[STACK-REF](https://stackoverflow.com/questions/55933708/unresolved-referenceactivitymainbinding/64017842#64017842)

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@smy5152 
Thank you for reaching out to us. We appreciate your feedback.
