### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by JuanSMartinez** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#343]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#7

**In which task and step of the codelab can this issue be found?**
Step 5 -> "Fit a carpet into a round dwelling"

**Describe the problem**
Is more a mathematical issue. The area of the largest square that fits into a circle is `diameter*diameter/2`, not `sqrt(diameter*diameter/2)`.

**Steps to reproduce?**
Not necessary

**Versions**
Not necessary

**Additional information**
Not necessary

**Comment by osuleymanova** [comment]
@JuanSMartinez 
Thank you for reaching out to us. The code snippet is updated and will be published soon:

![Screen Shot 2022-06-27 at 2 44 30 PM](https://user-images.githubusercontent.com/86437155/176041077-157fad48-7095-4cb6-ab60-3f00b48bf158.png)
