### ISSUE TITLE
Android Basics: change-app-icon

### ISSUE THREAD

**Issue by noc-turnal-dev** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#35]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-icon

**In which task and step of the codelab can this issue be found?**
"Move vector drawable files into -v26 directory"

**Describe the problem**
"Move vector drawable files into -v26 directory" section has dubious instructions and references options that do not exist where stated.

**Steps to reproduce?**
Step 1 of this section says, "First create the drawable-anydpi-v26 directory. Right click on the res folder. Select New > Android Resource Directory."
Step 2 says, "A prompt will appear. Select these options:
Resource type: drawable (Select from dropdown)

Directory name: drawable-anydpi-v26

Source set: main (leave as default)"

A prompt does appear, but there's no option or heading labeled "Source set".

Step 3, "Click OK. In the Project view, verify the new resource directory res > drawable-anydpi-v26 has been created."

Skipping the "Source set" stuff and clicking OK does not result in a new resource directory "res > drawable-anydpi-v26".  It instead makes a directory "res > drawable > drawable-anydpi-v26"

**Versions**
Android Studio 4.1.1
Build #AI-201.8743.12.41.6953283, built on November 4, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.4.58-07649-ge120df5deade
GC: ParNew, ConcurrentMarkSweep
Memory: 1246M
Cores: 4
Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin
Current Desktop: Undefined

**Additional information**

**Comment by jtavva** [comment]
@noc-turnal-dev 
Thank you for reaching out to us.
When the **New Resource Directory** dialog appears: 
**Source set** is the third option in the dialog, below **Resource type**.  You have to leave it as main.

![image](https://user-images.githubusercontent.com/24260141/99439791-82544e00-28ca-11eb-8f83-1db39bee8764.png)
To check the folder creation, switch to **Project** view. You can't check this in **Android** view.

![image](https://user-images.githubusercontent.com/24260141/99440388-5daca600-28cb-11eb-9074-24cc87d651e2.png)

Folder will be created under `res` directory. 

![image](https://user-images.githubusercontent.com/24260141/99439919-ae6fcf00-28ca-11eb-950d-9b8f78c867d6.png)

Hope this helps!
