### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by ef15c** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#352]
[**URL of codelab**](https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%3Fhl%3Den%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-instrumentation-tests&hl=en#3)

**In which task and step of the codelab can this issue be found?**
Paragraph "Implement the Test function" step 2

**Describe the problem**
The text is:
"The text is now entered and the test needs to click the Calculate button. The code for this follows a format similar to the one we used to enter text. The UI component is different, and so the id name that is passed to the **withText()** function is different. However, the only difference in the approach is that the ViewAction is different; the click() function is used instead of typeText()."

I think it should be:
"The text is now entered and the test needs to click the Calculate button. The code for this follows a format similar to the one we used to enter text. The UI component is different, and so the id name that is passed to the **withId()** function is different. However, the only difference in the approach is that the ViewAction is different; the click() function is used instead of typeText()."

**Steps to reproduce?**
N/A

**Versions**
N/A

**Additional information**
None.

**Comment by osuleymanova** [comment]
Hello @ef15c,

Thank you for reaching out to us and reporting this typo. It is fixed and republished:
![Screenshot 2023-03-31 at 3 31 44 PM](https://user-images.githubusercontent.com/86437155/229244393-a8e69936-8765-4177-9e03-189c6a7ec101.png)
