### ISSUE TITLE
Android Basics: xml-layouts

### ISSUE THREAD

**Issue by asaywitz** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#353]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%3Fhl%3Den%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-xml-layouts&hl=en#5

**In which task and step of the codelab can this issue be found?**
6. Complete the rest of the layout

**Describe the problem**
Earlier they said to use 0dp for layout_width for UI elements within a ConstraintLayout but in the example they show using match_parent

So they have:

<TextView
    android:id="@+id/tip_result"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    app:layout_constraintEnd_toEndOf="parent"
    app:layout_constraintTop_toBottomOf="@id/calculate_button"
    android:text="Tip Amount" />
    
    Should it be?
    
    <TextView
    android:id="@+id/tip_result"
    android:layout_width="0dp"
    android:layout_height="wrap_content"
    app:layout_constraintEnd_toEndOf="parent"
    app:layout_constraintTop_toBottomOf="@id/calculate_button"
    android:text="Tip Amount" />

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @asaywitz,

Thank you for reaching out to us and sharing your feedback. 
We updated the code snippet:

![Screenshot 2023-04-07 at 11 19 26 AM](https://user-images.githubusercontent.com/86437155/230658310-7cdba075-6c5b-4126-b162-593b916492e0.png)
