### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by qidCoder** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#354]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance

**In which task and step of the codelab can this issue be found?**
Task 3 step 5

**Describe the problem**
un-needed "val" in constructor. See snapshot

![image](https://user-images.githubusercontent.com/29787941/173076368-481a12f4-bf4a-4936-b3ae-560d5f7a3243.png)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by eungikim** [comment]
I was confused about this part, too!!

**Comment by osuleymanova** [comment]
@qidCoder, @eungikim 
Thank you for reaching out to us. The typo is fixed and will be published soon:

<img width="708" alt="Screen Shot 2022-06-27 at 2 25 54 PM" src="https://user-images.githubusercontent.com/86437155/176038676-21939dfd-9a17-4228-b03e-d054ccb2dd12.png">
