### ISSUE TITLE
Android Basics: xml-layouts

### ISSUE THREAD

**Issue by basd82** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#355]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-xml-layouts#4

**In which task and step of the codelab can this issue be found?**
RadioGroup 

**Describe the problem**

It is a typo in example you use for the last option okay an in the code OK

**Steps to reproduce?**
does not apply

**Versions**
does not apply

**Additional information**
<img width="752" alt="image" src="https://user-images.githubusercontent.com/1219705/173200046-673a0d92-44dd-40b1-90f7-436448d13680.png">

**Comment by osuleymanova** [comment]
@basd82 
Thank you for reaching out to us. The typo is fixed and  will be published soon:

![Screen Shot 2022-09-09 at 3 18 15 PM](https://user-images.githubusercontent.com/86437155/189453353-24857710-de1b-4eb2-be0f-5d27834164f6.png)
