### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by caoTayTang** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#356]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#3

**In which task and step of the codelab can this issue be found?**

On the task 'Calculate the tip' and the step 'Format the tip'.

**Describe the problem**

My phone is currently in Vietnam currency. So when I format the tip like your example code, It's got rounded up (even if the round_up_switch is NOT clicked), which is not what users want.

But when I change my phone's currency to US Dollar. It seems to work fine.

So there is a problem with auto rounding by NumberFormat(Locale).format() when the currency is not USD.

**Steps to reproduce?**
1. Run the solution code on Android Studio

https://github.com/google-developer-training/android-basics-kotlin-tip-calculator-app-solution

2. Change the currency of the phone to Vietnam dong for example.

3. Type in 50.00 at the Cost of Price TextEdit view. 
Toggle off the Round up tip switch. 
Choose radio button Okay (15%).
Then press Calculate.

**Versions**
_Android Studio version:_ Android Studio Chipmunk | 2021.2.1 Patch 1
_API version of the emulator:_ (I use my own phone)

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by caoTayTang** [comment]
` val formatter = NumberFormat.getCurrencyInstance()
  //This line turn off auto round of NumberFormat
  formatter.maximumFractionDigits = 4;
  val formattedTip: String = formatter.format(tip)
  binding.tipResult.text = getString(R.string.tip_amount, formattedTip)`
  If we add maximumFractionDegits then it works properly.

**Comment by osuleymanova** [comment]
@caoTayTang 
Thank you for reaching out to us and sharing your observation and further solution.
