### ISSUE TITLE
Android Basics: change-app-theme

### ISSUE THREAD

**Issue by yash1081** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#361]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-theme#7)

**In which task and step of the codelab can this issue be found?**On the learn more section there is no option for done and move to next task

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@yash1081 
Thank you for reaching out to us. We'll check this.
