### ISSUE TITLE
Android Basics: xml-layouts

### ISSUE THREAD

**Issue by ishu303** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#362]
https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-xml-layouts#3

In activity 4 (build the layout in XML) , heading -**Delete the TextView** under this step one ,code no. two

**Describe the problem**
from the last 2 line of the code it is written that   **tools:context=".MainActivity">**  but there is mistake before MainActivity .there is a dot before it which make error in XML code and mark as a problem.

**Steps to reproduce?**
1. go to Get user input in an app: Part 1
2. Click on... Codelab 4 then click on build the layout in XML
3. See error...scroll done to the heading **Delete the TextView** in code 2 see from last second line.

**Versions**
_Android Studio version:_ VERSION_1_8
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Screenshot (1)](https://user-images.githubusercontent.com/108219379/180767647-bfb87d7a-dde9-42aa-84b1-4dbdd2c2955e.jpg)

**Comment by osuleymanova** [comment]
@ishu303 
Thank you for reaching out to us and providing the screenshot. From first glance it seems 2 projects "Tip Time" and "Birthday card" are mixed up. 

![Screen Shot 2022-09-09 at 1 07 09 PM](https://user-images.githubusercontent.com/86437155/189435064-d2bcd418-c518-4423-b1bc-f2b7ff113cb7.png)

Creating the Tip time app there is no mistake in tools:context=".MainActivity"> , the dot(.) should be in front of MainActivity, the build runs successfully, no error messages. Please be sure that you follow the steps of codelab: https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts#0.
