### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by wemorgan-zoho-eu** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#363]
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#5

In "Adopt Good Programming Practices"

It says:
> choose **Analyze > Inspect Code**... in the menus

But it should be:  **Code > Inspect Code**

**Comment by osuleymanova** [comment]
@wemorgan-zoho-eu 
Thank you for reaching out to us. In the screenshots below you can see 2 options of opening the window for inspecting the code:

![Screen Shot 2022-09-13 at 11 37 10 AM](https://user-images.githubusercontent.com/86437155/189987678-fca31275-4850-4337-ae4d-dbb9cbb9b25e.png)

![Screen Shot 2022-09-13 at 11 39 59 AM](https://user-images.githubusercontent.com/86437155/189987728-eca656de-5893-4b76-9adb-10954a4465b9.png)


Taking this fact into consideration the instructions in the codelab  will be updated.
