### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by clintonmagro** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#364]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#3

**In which task and step of the codelab can this issue be found?**
4

**Describe the problem**
The text says the following "but in Euros, it would be formatted €1.234,56." this is only true for countries like Italy. Most places in Europe we use the comma to separate thousands and the dot for decimals. 

**Steps to reproduce?**
N/A

**Versions**
N/A

**Additional information**
N/A

**Comment by osuleymanova** [comment]
@ @clintonmagro 
Thank you for reaching out to us and sharing this information. This is in contrast with how large numbers are formatted in the United States. We'll keep  this fact in mind when creating a codelab next time.
