### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by ejtorcello** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#366]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#6
**In which task and step of the codelab can this issue be found?**

**Describe the problem**
I am quite newbie 

I can't get the code working as I downloaded

It worked when I replaced
binding.tipResult.text = getString(R.string.tip_amount, formattedTip)
 by

  binding.tipResult.text = formattedTip.toString()

**Comment by osuleymanova** [comment]
@ejtorcello 
Thank you for reaching out to us.
Please provide the screenshot of the error so that we can help you with troubleshooting.

**Comment by osuleymanova** [comment]
Closing this issue, since there is no response. It looks like you found the problem solution.
Please create a new one, if you need help.
All the best learning Android.
