### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by disala** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#37]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator#2

**In which task and step of the codelab can this issue be found?**
3. View binding

**Describe the problem**

Section -> Enable view binding

buildFeatures {
    viewBinding = true
}
Should change to 

android {

    viewBinding.enabled = true

With newer version

**Comment by jtavva** [comment]
@disala 
Thank you for reaching out to us.

To enable view binding in your app, the code given in the codelab is correct. 
Reference documentation: https://developer.android.com/topic/libraries/data-binding/start#build_environment
