### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by StevieLark** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#376]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#2

**In which task and step of the codelab can this issue be found?**
Enable view binding

**Describe the problem**
It does not work and produce an error in the MainActivity.kt

**Steps to reproduce?**
If you put in this code, is does not work:

buildFeatures {
    viewBinding = true
}

Instead of this I tried this and it worked fine then:
buildFeatures {
   { viewBinding = true}
}

**Versions**
_Android Studio version:_ built from May 2022
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@StevieLark 
Thank you for reaching out to us and sharing your concern.
Both variants are possible so it's good that you found your own.
Happy coding!
