### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by 1slash77** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#377]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#3

**In which task and step of the codelab can this issue be found?**
step 2: setOnClickListener() now requires fun with returned value of View.OnClickListener?
A moment later: val stringInTextField = binding.costOfService**.text** is Editable object but not String. Should be replaced to .toString()
 

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @1slash77,

Thank you for reaching out to us and reporting this issue. It is fixed:

![Screenshot 2023-03-31 at 3 58 48 PM](https://user-images.githubusercontent.com/86437155/229251332-555d502e-176c-4853-8127-91ed88072862.png)
