### ISSUE TITLE
Android Basics: change-app-icon

### ISSUE THREAD

**Issue by doraba** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#38]
**URL of codelab** 
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-icon#2

**In which task and step of the codelab can this issue be found?**
At step 4

**Describe the problem**
For example, this is what res > mipmap-xxhdpi > ic_launcher_round.png looks like. Also notice the size of the asset is in the top right. This image is 192px x 192px in size.

**xxhdpi** should be replaced with **xxxhdpi**

**Comment by jtavva** [comment]
@doraba 
Thank you so much for reporting this issue. This is fixed and will be published soon.
