### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by hassan0599** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#381]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-instrumentation-tests#3

**In which task and step of the codelab can this issue be found?**
Task 4 -> Implement the Test function -> Bullet point 2

**Describe the problem**
The text reads _"...The UI component is different, and so the id name that is passed to the withText() function is different. ..."_ and should instead read _"The UI component is different, and so the id name that is passed to the **withId()** function is different."_

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Screenshot 2022-09-06 180309](https://user-images.githubusercontent.com/61388284/188748521-e6e3ab22-3034-4c8a-aa1d-aeebdffe4fdc.png)

**Comment by hassan0599** [comment]
This issue hasn't been resolved. Kindly fix this asap

**Comment by osuleymanova** [comment]
@hassan0599 
Thank you for reaching out to us. The typo is fixed:

![Screen Shot 2022-11-08 at 10 31 44 AM](https://user-images.githubusercontent.com/86437155/200647159-fe117efd-5dad-4ddb-b708-e4651ff80843.png)
