### ISSUE TITLE
Android Basics: polished-user-experience

### ISSUE THREAD

**Issue by t1eap** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#39]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-polished-user-experience?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-polished-user-experience#3

**In which task and step of the codelab can this issue be found?**
Android Basics Kotlin Unit 2 Pathway 1
Create a More Polished User Experience
Section 4 Icons
Step 6

**Describe the problem**
The code snippit says:

`   <ImageView
        android:id="@+id/icon_service_question"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:importantForAccessibility="no"
        app:srcCompat="@drawable/ic_service"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="@id/service_question"
        app:layout_constraintBottom_toBottomOf="@id/service_question" />

    <TextView
        android:id="@+id/service_question"
        ...
        android:layout_marginTop="16dp"
        app:layout_constraintStart_toEndOf="@id/icon_service_question" />
`

Specifically `app:layout_constraintStart_toEndOf="@id/icon_service_question"` is the main point of interest

Based on https://github.com/google-developer-training/android-basics-kotlin-tip-calculator-app-solution/blob/main/app/src/main/res/layout/activity_main.xml#L73, I believe it should be

`
    <TextView
        android:id="@+id/service_question"
        ...
        android:layout_marginTop="16dp"
        app:layout_constraintStart_toStartOf="@id/cost_of_service"
        app:layout_constraintTop_toBottomOf="@id/cost_of_service"/>
`

Prior to looking up the solution by jumping ahead to the solution code, I was unable to get the TextView's left side to align with the Material TextInputLayout above it; the TextView would be on top of the icon.

**Steps to reproduce?**
Follow the codelabs tutorial.

**Versions**
N/A

**Additional information**

**Comment by jtavva** [comment]
@t1eap 
Thank you so much for reporting this issue. This is fixed and will be published soon.
