### ISSUE TITLE
Codelabs: Formatting Issue on Mobile Device

### ISSUE THREAD

**Issue by t1eap** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#40]
**URL of codelab**
Any codelab page.  Needs to be on mobile device.

Example: https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-theme?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-change-app-theme#2

**Describe the problem**
This isn't specific to any single codelab; it applies to all of them.

When viewing using Chrome 86.0.4240.185 on my Pixel 2, the "Next" and "Back" buttons are cut off almost entirely.  It's as if the android bar with the triangle (back), circle (home), and square (recent apps) is not accounted for and it overlays on top of the "Back" and "Next" buttons in codelab.  See screenshot attachment.

I am viewing using the mobile view.  If I select "Use desktop view" in Chrome, the buttons are not visible at all.

**Steps to reproduce?**
1. Navigate to a codelab page (i.e. the actual module with the steps on the left side) in Chrome on a Pixel 2 (suspect any mobile device will work).

**Versions**
Chrome 86.0.4240.185 
Pixel 2

**Additional information**
See screenshots
![Screenshot_20201116-054316](https://user-images.githubusercontent.com/37046423/99249318-894a6600-27cf-11eb-9b9b-b9f718428e48.png)
![Screenshot_20201115-214710](https://user-images.githubusercontent.com/37046423/99249323-8bacc000-27cf-11eb-8f17-5ba8203eeb4a.png)

**Comment by jkcoolmom** [comment]
Thank you so much for flagging this issue - we have reported it to the appropriate team for their attention.
