### ISSUE TITLE
Android Basics: change-app-icon

### ISSUE THREAD

**Issue by TedHopp** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#42]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-icon?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-change-app-icon#2

**In which task and step of the codelab can this issue be found?**

Step 3: Launcher Icons

**Describe the problem**

Under Explore Launcher Icons, the text of the tutorial says to click on the image file to see a preview. However, clicking isn't enough unless one has enabled "Open Files wIth Single Click". It would be more accurate to say that you need to open the image file in Android Studio to see the preview.

Also, the tutorial says to click on **res > mipmap-xxhdpi > ic_launcher_round.png** and to notice that the image is 192 x 192 pixels. However, the image is 142 x 142 pixels. The 192 x 192 image is in the **res > mipmap-xxxhdpi** folder

**Steps to reproduce?**
1. Go to...**res > mipmap-xxhdpi**
2. Click on...**ic_launcher_round.png** (or double click if needed to open)
3. See error...The preview pane displays the size of the asset as 144x144, not 192x192

**Versions**
_Android Studio version:_ 4.1.1
_API version of the emulator:_ N/A

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@TedHopp 
Thank you for reaching out to us.
This should be fixed now.
