### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by Masirika2** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#428]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
WHY THE CODE LAB FOR THE MainActivity.kt are not working in my project 

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @Masirika2 ,

Please provide the detailed information about what issue you are facing.
