### ISSUE TITLE
Android Basics: polished-user-experience

### ISSUE THREAD

**Issue by srLitem** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#43]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-polished-user-experience?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-polished-user-experience#5

**In which task and step of the codelab can this issue be found?**
Step 6

**Describe the problem**
The 4th paragraph of the section **(Optional) Adjust the tint of the vector drawables** has a typo:
_One visual enhancement we can make to the app is to tint the drawable based on the primary color of the app theme. `BFor` light theme, the icon will appear..._

The typo is as seen Before, **"Bfor"**.

**Steps to reproduce?**
1. Go to the codelab.
2. Click on the 6th step
3. See error on 4th paragraph of the section **(Optional) Adjust the tint of the vector drawables** section.

**Versions**
_Android Studio version:_  N/A
_API version of the emulator:_ N/A

**Additional information**
![image](https://user-images.githubusercontent.com/29027903/99483250-d2afc800-292b-11eb-98ed-18378668e5e9.png)

**Comment by jtavva** [comment]
@srLitem 
Thank you for reaching out to us.
This should be fixed now.
