### ISSUE TITLE
Android Basics: change-app-theme

### ISSUE THREAD

**Issue by cstechsandesh** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#432]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-theme?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-change-app-theme#1

**In which task and step of the codelab can this issue be found?**
Step 2 => Design and color

**Describe the problem**
In sub section "A bit about color"
Alpha value is not the first two characters after "#" but are the last two characters.

**Additional information**
![image](https://user-images.githubusercontent.com/47110921/224234348-bfb5e3a3-8245-47bf-a3dd-97c54b9b38e0.png)

**Comment by SebastianWozniczka** [comment]
Good morning. Transparency works for me the same as in the course: 
`<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="purple_200">#00BB86FC</color>
    <color name="purple_500">#006200EE</color>
    <color name="purple_700">#003700B3</color>
    <color name="teal_200">#0003DAC5</color>
    <color name="teal_700">#00018786</color>
    <color name="black">#00000000</color>
    <color name="white">#00FFFFFF</color>
</resources>`
