### ISSUE TITLE
Android Basics: change-app-icon

### ISSUE THREAD

**Issue by GregBradb** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#44]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-icon?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-change-app-icon#5

**In which task and step of the codelab can this issue be found?**
6 - Change the app icon

**Describe the problem**
Under "Move vector drawable files into -v26 directory
Depending on the min SDK of your app, you may notice that the background asset is located in the drawable-v24 folder, while the foreground asset is in the drawable folder. The reason is because the background asset contains a gradient, which was available starting in the Android 7.0 release (also known as API version 24, hence the -v24 resource qualifier). The foreground asset doesn't contain a gradient, so that can go in the base drawable folder."

The references to foreground and background have been switched.  The foreground file is in the drawable-v24 folder and has a gradient.  The background doesn't have a gradient.

**Steps to reproduce?**
1. Go to... the URL given above and then to the "Move vector drawable files into -v26 directory" section
2. Click on...
3. See error...

**Versions**
_Android Studio version:_  N/A
_API version of the emulator:_  N/A

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@GregBradb 
Thank you so much for reporting this issue. This is fixed and will be published soon.
