### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by MohamadMF** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#45]
**URL of codelab**
_https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#3_

**In which task and step of the codelab can this issue be found?**
_Google Developer course to learn build and program an android apps. In unit 2: Layouts, Calculate the Tip codelab._

**Describe the problem**
_ I found a difference between the two showing. In codelab they ask me to put this Code:

class MainActivity : AppCompatActivity() {

    lateinit var binding: ActivityMainBinding

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root)
        binding.calculateButton.setOnClickListener{ calculateTip() } 
    }

    fun calculateTip() {

    }
}

but when I put it into Android Studio I found this wrong alert as this screenshot. And there's no any guidance in the codelab shows that I could find an issue as usual

So. What should I do?_

**Versions**
_Android Studio version: 4.1.1_ 

**Additional information**
_A screenshot_
![2020-12-04 (1)](https://user-images.githubusercontent.com/72653078/101210073-93001480-367d-11eb-951a-a8050052445c.png)

**Comment by hgwigueras** [comment]
I have the same issue, how did you fix it? @MohamadMF
