### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by vadkad8** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#457]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#0)

**7. Solution code**

**fun displayTip(tip) isn't used (described in 6. Adopt good coding...)**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jlulovics** [comment]
thank you for taking the time to provide feedback. this content has been deprecated. Please visit https://developer.android.com/courses/android-basics-compose/course for the latest recommended best practices for Android development.
