### ISSUE TITLE
Android Basics: xml-layouts

### ISSUE THREAD

**Issue by Mariaines24** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#459]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts?hl=pt-br&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%3Fhl%3Dpt-br%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-xml-layouts#3)

I don´t know if its a mistake but, 1st we don´t have the version 19, just 21. Then the file activity_main.xml does not exists in the project so I can´t continue the task.

<img width="1440" alt="Captura de ecrã 2023-10-11, às 09 49 12" src="https://github.com/google-developer-training/android-basics-kotlin-tip-calculator-app-solution/assets/128185971/964907e4-2c2f-45f7-abd7-bbada82ee4f1">
<img width="896" alt="Captura de ecrã 2023-10-11, às 09 48 12" src="https://github.com/google-developer-training/android-basics-kotlin-tip-calculator-app-solution/assets/128185971/55806876-554f-41b7-9230-8a50e8413e9d">

**Comment by Krunal-375** [comment]
is this issue still present?

**Comment by jlulovics** [comment]
thank you for taking the time to provide feedback. this content has been deprecated. Please visit https://developer.android.com/courses/android-basics-compose/course for the latest recommended best practices for Android development.
