### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by Big-Chinguss** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#46]
**https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#4**

**Task 5**

**It is a very basic query regarding the floorArea function, which when we are using for roundTower, should have the formula, PI*radius*radius, as the formula which is stated by you is valid for the volume, because it's unit is meter-cube, not meter-square, so either correct the formula or correct the name for function used.**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@Big-Chinguss 
Floor area of a circle is meter square not meter cube.
You can refer any website like [this one](https://www.smartconversion.com/unit_calculation/Area_of_a_Circle.aspx)
Thank you for reaching out to us.
