### ISSUE TITLE
Android Basics: change-app-theme

### ISSUE THREAD

**Issue by MoeJoeMJ** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#460]
[URL of codelab](https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-theme?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-change-app-theme#3)

**In which task and step of the codelab can this issue be found?**
Step 4. Line 2.

**Describe the problem**
The link to the color tool isn't actually taking us to the tool

**Comment by jlulovics** [comment]
thank you for taking the time to provide feedback. this content has been deprecated. Please visit https://developer.android.com/courses/android-basics-compose/course for the latest recommended best practices for Android development.
