### ISSUE TITLE
Virtual Device not running the layout activity

### ISSUE THREAD

**Issue by Alfonsoml34** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#461]
**URL of codelab**
[Create XML layouts for Android]

(https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-xml-layouts)

**In which task and step of the codelab can this issue be found?**
Step 4

**Describe the problem**
First of all, I wasn't able to find the layout folder but managed to understand that I have to create one.
The real issue is that when running the xml I don't see it reflected on the virtual device and it is only showing the MainActivity.kt result

**Steps to reproduce?**
1. You can copy the xml solution code and run the virtual device

**Comment by jlulovics** [comment]
thank you for taking the time to provide feedback. this content has been deprecated. Please visit https://developer.android.com/courses/android-basics-compose/course for the latest recommended best practices for Android development.
