### ISSUE TITLE
Android Basics: polished-user-experience

### ISSUE THREAD

**Issue by Kb-Bojang** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#47]
https://developer.android.com/codelabs/basic-android-kotlin-training-polished-user-experience?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-polished-user-experience#4

**_Styles and Themes_**

I type this code in "<item name="switchStyle">@style/Widget.TipTime.CompoundButton.Switch</item>" and got the red error text for the "@style/Widget.TipTime.CompoundButton.Switch", and I tried copying it direct but the result was same. Eventually, I tweaked it till it work and the resulting code I ended up with is "<item name="switchStyle">@style/Widget.TipTime.Switch</item>". The codes seems fine but since am only learning, am sure it is right but wanted to highlight this in case some else gets stuck at that same exercise

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 4.1.1
_API version of the emulator:_ 25
![ThemesAndStyles](https://user-images.githubusercontent.com/75809735/101825123-1bbafc80-3b25-11eb-920a-b913a6502a86.JPG)

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@Kb-Bojang 
Thank you for reaching out to us.
I think in your code you missed a step to add the following style in `values/styles.xml `
If you add this style the code will work as intended. 

```
<!-- Switch style -->
    <style name="Widget.TipTime.CompoundButton.Switch" parent="Widget.MaterialComponents.CompoundButton.Switch">
        <item name="android:minHeight">48dp</item>
        <item name="android:gravity">center_vertical</item>
        <item name="android:textAppearance">?attr/textAppearanceBody1</item>
    </style>
```

Please refer this file: https://github.com/google-developer-training/android-basics-kotlin-tip-calculator-app-solution/blob/main/app/src/main/res/values/styles.xml

**Comment by Kb-Bojang** [comment]
@jtavva thanks so for much helping me out, I really appreciate it (and sorry for taking a bit long to reply show my appreciation,). After comparing your solution to my code, I realised that I forgot to add "CompoundButton" in the "<style name"Widget.TipTime.CompoundButton.Switch" ...". :)
