### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by WisdomSays** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#48]
**URL of codelab** [Here](https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#3)

**In which task and step of the codelab can this issue be found?**
CALCULATE TIP - STEP 3 (VIEW BINDING)

**Describe the problem**
Following through the steps, while initializing the binding object. I am required to replace **all** existing code in the ```MainActivity.kt``` file with the provided code snippet which didn't include defining ```package com.example.tiptime```, which later caused an error in the ```activity_main.xml``` causing the App to crash.

**Steps to reproduce?**
1. Just include ```package com.example.name``` which in my case ```package com.example.tiptime``` at the very top of the ```MainActivity.kt``` file.

**Comment by Utsav2115** [comment]
Hey Wisdom,
In the second step of **Initialize the binding object** the following statement is written:
"**Replace all of the existing code for **MainActivity class** with this code to setup the MainActivity to use view binding:**"
So, I think you missed the "class" word. Accordingly, this means that you have to just replace the MainAcitvity class ,i.e, starting from "class MainActivity : AppCompatActivity()" till the closing curly bracket of that class and hence not the whole code in the MainActivity.kt file. Also, as you had removed the whole code in the "MainActivity.kt" file,  all the import code would had been removed and hence this would have caused some problem in the working of your code.
Hope this helps you.

**Comment by jtavva** [comment]
@Utsav2115 Thank you so much for replying to the query.
@WisdomSays, we hope that resolves your question. 

We are closing this ticket. You can always reopen this ticket or raise a new one if you need any further assistance.
