### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by Utsav2115** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#49]
URL:
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?authuser=3&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%3Fauthuser%3D3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#2

Task and the Step:
                       Task: Adopting good coding practices
                       Step: Inspect the code

Problem:
            According to the documentation in the Inspect Code Step of this task, an option starting with text  "file..." should be there. But I couldn't find it in my android studio. Please refer the images below:

Documentation Image:
![Documentation Image](https://user-images.githubusercontent.com/64418023/102264036-169de900-3f3b-11eb-93f9-2b1074e222a5.png)

Android Studio Image:
![Android Studio Screenshot](https://user-images.githubusercontent.com/64418023/102264391-91670400-3f3b-11eb-8cd3-4434a6ca4ab3.png)
_Android Studio version:_ 4.1.1 for Windows 64-bit

             

Please help :)

**Comment by jtavva** [comment]
@Utsav2115 
Thank you for reaching out to us.
To troubleshoot your issue, please follow the following steps: 
1. Click somewhere on the file before making the choosing **Analyze > Inspect Code…** in the menus. which should do the same operation. 
2. If the first step does not work, us can use the **Custom scope > current file** option as shown below. 
![image](https://user-images.githubusercontent.com/24260141/102827906-4e23ef80-4398-11eb-938e-a6c252648102.png)
