### ISSUE TITLE
Android Basics: xml-layouts

### ISSUE THREAD

**Issue by Tibor42** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#5]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts?return=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-xml-layouts#3

**In which task and step of the codelab can this issue be found?**
At the end of the page of step 4: Create XML layouts for Android

**Describe the problem**
Typo / copy and paste error:

In the last code-example:
"At this point, your XML should look like this."
The textview still has the copied id from the EditView (@+id/cost_of_service) instead of the before mentioned @+id/service_question

i know this is a very minimal issue, and considered before making this issue/report.
But when i notice issues like that, i always start to question the overall quality of the work that people put into something.
So i think it would be nice if it would be fixed, for the benefit of the people doing this course later.

:-)
and isn't it nice that so far no bigger issues came up? 

best regards

**Comment by jtavva** [comment]
Thank you for reaching out to us.
The id for EditView is `@+id/cost_of_service`
The id for TextView is `@+id/service_question`

The code in the snippet shown is as follows:

```
     <EditText
        android:id="@+id/cost_of_service"
         .... />


    <TextView
        android:id="@+id/service_question"
        ........
        app:layout_constraintTop_toBottomOf="@id/cost_of_service"/>
```

Which is correct, if there is something still wrong please reopen this issue. Thank you.
