### ISSUE TITLE
Android Basics: change-app-theme

### ISSUE THREAD

**Issue by Lurosk** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#51]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-theme?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-change-app-theme

**In which task and step of the codelab can this issue be found?**
Task 3: Themes. Last section, step 4.

**Describe the problem**
The code that we are asked to copy uses the item name: colorPrimaryDark. However, the following image (in step 5) showing the coloured squares on the code line numbers uses the name colorPrimaryVariant, and the rest of the tutorial refers to colorPrimaryVariant too.

**Additional information**
![image](https://user-images.githubusercontent.com/19304907/102305850-14787080-3fb5-11eb-918a-cb15e88af3ee.png)
![image](https://user-images.githubusercontent.com/19304907/102305906-3114a880-3fb5-11eb-92cc-18e2bf7805d6.png)

**Comment by jtavva** [comment]
@Lurosk 
Please provide us with the following details:
1. Android studio version:

**Comment by jtavva** [comment]
@Lurosk 
It's been months since we've heard from you, so we are going to close this ticket. You can always reopen this ticket or raise a new one if you need any further assistance.
