### ISSUE TITLE
Android Basics: polished-user-experience

### ISSUE THREAD

**Issue by dlange2112** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#53]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-polished-user-experience?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-polished-user-experience#3

**In which task and step of the codelab can this issue be found?**
Icons/Step 6

**Describe the problem**
The solution code has a layout_width attribute on the cost_of_service TextInputLayout, but no mention of adding it, or why it's there, is in the description of this step.

**Comment by jtavva** [comment]
@dlange2112 
Under task **[3 Material components](https://developer.android.com/codelabs/basic-android-kotlin-training-polished-user-experience?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-polished-user-experience#2)** it is mentioned to set the  layout_width attribute to 160dp. 

![image](https://user-images.githubusercontent.com/24260141/102822636-55460000-438e-11eb-8cfe-94556c0cef1f.png)

Thank you for reaching out to us.
