### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by qvmzs** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#54]
**URL of codelab**
[Calculate the tip](https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?hl=ja&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%3Fhl%3Dja%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#3)

**In which task and step of the codelab can this issue be found?**
4 Calculate the tip -> Display the tip

**Describe the problem**

`binding.tipResult.text = getString(R.string.tip_amount, formattedTip)`
should be
`binding.tipAmount.text= getString(R.string.tip_amount, formattedTip)`

![before](https://i.imgur.com/9IQZ9Qy.png)
![after](https://i.imgur.com/xqM8wiM.png)

**Comment by jtavva** [comment]
@qvmzs 
Thank you for reaching out to us.
The code snippet is correct in the codelab. Text view ID is `tip_result`

```
 <TextView
        android:id="@+id/tip_result"
        style="@style/Widget.TipTime.TextView"
        ...
        tools:text="Tip Amount: $10"
        />
```

Please verify your activity_main.xml. 
https://github.com/google-developer-training/android-basics-kotlin-tip-calculator-app-solution/blob/3662e275a97e6e577287613b10fcbf20c2ff0ac8/app/src/main/res/layout/activity_main.xml

Please provide your activity_main.xml file, if you still face the issue.
