### ISSUE TITLE
Reinitializing the 'residents' property in RoundHut class with var

### ISSUE THREAD

**Issue by nuel-ikwuoma** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#55]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#5

**In which task and step of the codelab can this issue be found?**
lasses and inheritance in Kotlin

**Describe the problem**
I noticed the residents property was reintialized with a var keyword in the RoundHut open class, even though it has been declared in the parent Dwelling class.

I am wondering if this is a mistake or intentional, as it does seem to cause any major error in the code for now

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@nuel-ikwuoma 
Thank you for reaching out to us.
`residents` property is inherited from the parent class. That means you can use it with out declaring it, and you can change its value inside the child class. 

![image](https://user-images.githubusercontent.com/24260141/102823817-790a4580-4390-11eb-94bf-11b124973ba8.png)

**Comment by nuel-ikwuoma** [comment]
I made mention of 'residents' property been redeclared in the 'RoundHut' class, not in 'SquareCabin'

Please check the 'RoundHut' class constructor.

**Comment by jtavva** [comment]
@nuel-ikwuoma 
The same explanation is valid for `RoundHut` class as well. 
`residents` property is inherited from the parent class. That means you can use it with out declaring it, and you can change its value inside the child class.

![image](https://user-images.githubusercontent.com/24260141/103024319-72044400-4504-11eb-877e-4d535a4dacb9.png)

**Comment by nuel-ikwuoma** [comment]
The problem actually occured in the [solution code](https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#5)

![roundhut_](https://user-images.githubusercontent.com/30737582/103081197-c1677480-45d7-11eb-8e51-f5be96de1696.png)

In the image shown above, `residents` was re-declared as `val` in the `RoundHut` subclass, even tho this property was already delared with `private var` in the `Dwelling` superclass.

Please use the link above :point_up_2: to verify this issue.

**Comment by nuel-ikwuoma** [comment]
Is this issue still invalid?

**Comment by osuleymanova** [comment]
@nuel-ikwuoma 
Thank you for reaching out to us. The issue is fixed and will be published soon:

open class RoundHut(residents: Int) : Dwelling(residents) {  

 override val buildingMaterial = "Straw"
 override val capacity = 4
}
