### ISSUE TITLE
Android Basics: xml-layouts

### ISSUE THREAD

**Issue by zsivm** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#56]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-xml-layouts#5

**In which task and step of the codelab can this issue be found?**
At task: Add Calculate Button
Step 4.

**Describe the problem**
There is a typo at "Add Calculate Button":
4. GIve it a resource ID of @+id/calculate_button, with the text "Calculate".

The "i" is capital after "G".

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@jtavva 
Thank you so much for reporting this issue. This is fixed and will be published soon.
