### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by man4ever84** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#58]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#2

**In which task and step of the codelab can this issue be found?**
The screenshot under title "Enable view binding" in section "#3 View Binding" has a typo.

**Describe the problem**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator/img/8f7cc689b80e77e8.png
"buildFeature" is misspelled in the screenshot.

**Comment by jtavva** [comment]
@man4ever84 
Thank you so much for reporting this issue. This is fixed and will be published soon.
