### ISSUE TITLE
Android Basics: Next button is missing - tip-calculator

### ISSUE THREAD

**Issue by QatarCoin** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#59]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator#10

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
1. The comment mentions a Unit Converter but the app was a Tip Calculator
2. There is no Next button

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@artnkfv 
Thank you for reporting this issue. It was fixed and published
