### ISSUE TITLE
Android Basics: Area of square inside a circle - classes-and-inheritance

### ISSUE THREAD

**Issue by Cathie1953** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#61]
**URL of codelab**https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#4

**In which task and step of the codelab can this issue be found?** Step 5

**Describe the problem** How is the formula for fitting a rectangle into a circle  equal to the square root of the diameter squared divided by 2: sqrt (diameter * diameter / 2)?  If I have a circle with a 12' diameter, I need a 12' x 12' piece of carpet, don't I?
I got an answer of 14' square to cover 314 sf.  14' square = 196 SF.  I am very new, so I definitely could be wrong.

**Steps to reproduce?**
1. Go to...Fit a carpet into a round dwelling
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@Cathie1953 
Thank you so much for reporting this issue. This is fixed and will be published soon.
