### ISSUE TITLE
Android Basics: xml-layouts

### ISSUE THREAD

**Issue by vivaan19** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#62]
**URL of codelab**

--> 
https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-xml-layouts#3

**In which task and step of the codelab can this issue be found?**

--> Its the fourth task named "Built layouts in XML"

**Describe the problem**

--> There is a line of code for "padding" missing in the "constraint layout" section of the code (i.e the first few lines of code), the extra line would be : android:padding="16dp" 

**Steps to reproduce?**(not required)
1. Go to...
2. Click on...
3. See error...

**Versions**(not required)
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**(not required)
_Include screenshots if they would be useful in clarifying the problem._ 
--> No SS required

**Comment by jtavva** [comment]
@vivaan19 
Thank you so much for reporting this issue. This is fixed and will be published soon.
