### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by Cathie1953** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#63]
**URL of codelab**https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#3

**In which task and step of the codelab can this issue be found?**  #5 calculate the tip step 4

**Describe the problem** We are never told to go through and extract the string references.  However, I did do that, accepting defaults.  There is no "tip_result".  There is "tip_amount".
Codelab instructions:
Open strings.xml (app > res > values > strings.xml); Change the tip_amount string from Tip Amount to Tip Amount: %s.

<string name="tip_amount">Tip Amount: %s</string>
The %s is where the formatted currency will be inserted.

Now set the text of the tipResult. Back in the calculateTip() method in MainActivity.kt, call getString(R.string.tip_amount, formattedTip) and assign that to the text attribute of the tip result TextView.

binding.tipResult.text = getString(R.string.tip_amount, formattedTip)

**Steps to reproduce?**
1. Go to...binding.tipResult.text = getString(R.string.tip_amount, formattedTip)
2. Click on...
3. See error...tipResult is red and it said to rename the reference
4. When I changed binding.tipResult to binding.tipAmount, everything worked
The codelab final solution reflects "tipResult" as well.

 

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@Cathie1953 
Thank you for reaching out to us. The code provided in the codelab is correct, no content update is needed.
