### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by Edgar158** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#65]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance#4

**In which task and step of the codelab can this issue be found?**
8

**Describe the problem**
Original constructor of RoundHut (per previous exercise) was:
open class RoundHut(residents: Int, val radius: Double) : Dwelling(residents) {
While in the example code is shown as follows:
open class RoundHut(val residents: Int, val radius: Double) : Dwelling(residents) {
val residents argument was added from nowhere, it does not affect the code though.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@Edgar158 
Thank you for reaching out to us. The issue is fixed and will be published soon:
open class RoundHut(
       residents: Int, val radius: Double) : Dwelling(residents) {
