### ISSUE TITLE
Android Basics: classes-and-inheritance - wrong carpet size calculation

### ISSUE THREAD

**Issue by hhhao** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#67]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance#4

**In which task and step of the codelab can this issue be found?**
Fit a carpet into a round dwelling

**Describe the problem**
In calculateMaxCarpetSize of step 2, the returned quantity is the side of the square carpet that can fit in the floor, and not the area. An easy way to check is that the dimension is not that of length^2. The actual area of the carpet is diameter^2 / 2.
I assumed by carpet size it means area. This section could use better wording.

**Comment by osuleymanova** [comment]
@hhhao 
Thank you for reaching out to us. We considered your suggestion so the issue is fixed and will be published soon:
fun calculateMaxCarpetLength(): Double {    
    return sqrt(2.0) * radius
    }
