### ISSUE TITLE
Android Basics: polished-user-experience

### ISSUE THREAD

**Issue by regardliss** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#68]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-polished-user-experience?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-polished-user-experience#2

**In which task and step of the codelab can this issue be found?**

Switches/Step 2
**Describe the problem**
xml tag contains period for the end of the sentence

Screenshot:
![image](https://user-images.githubusercontent.com/56805840/106389193-1739f400-63b0-11eb-9e6c-3d1c9f18bcd0.png)

**Comment by jtavva** [comment]
@regardliss 
Thank you for reaching out to us.
That period(.) is for the end of the sentence, you can copy the XML tag from the code snippet.
