### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by yalematta** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#69]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator

**In which task and step of the codelab can this issue be found?**
Step 4 - Get the tip percentage

**Describe the problem**
Just a typo: should **be** like this
```
At this point, the calculateTip() method should like this:
```

**Comment by osuleymanova** [comment]
@yalematta 
Thank you for reaching out to us. The issue is fixed and published.
