### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by DanielTatarkin** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#7]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?return=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#2

**In which task and step of the codelab can this issue be found?**
Section "Create an abstract Dwelling class"

- Step 2 and 8

**Describe the problem**

Step 2 mentions deleting all code in the editor, while I believe it means just removing the println("Hello, world!") part inside main()

Step 8 asks us to put code inside main() which may have been deleted due to the way Step 2 is written

**Steps to reproduce?**
Read step 2, then proceed with next steps until step 8

**Comment by jtavva** [comment]
Thank you so much for reporting this issue. This is fixed and will be published soon.
