### ISSUE TITLE
Android Basics: polished-user-experience

### ISSUE THREAD

**Issue by Carlos-AMx** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#70]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-polished-user-experience?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-polished-user-experience#5

**In which task and step of the codelab can this issue be found?**
Hide keyboard on Enter key

**Describe the problem**
keyEvent is not recognized with the command:
KeyEvent.KEYCODE_ENTER

The Enter Key automatically hides the keyboard, I'm testing with Android Studio 4.1.2 

**Steps to reproduce?**
1. Hide keyboard on Enter key step one
2. add the code keyCode == KeyEvent.KEYCODE_ENTER
3. create local variable as the command is not recognized

**Versions**
_Android Studio version: 4.1.2
_API version of the emulator:_ 30
![keyEvent error](https://user-images.githubusercontent.com/65750658/107107017-31326700-67f4-11eb-94a5-1b7786388a0e.PNG)

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by amberream** [comment]
Running into the same thing testing on my phone (running Android 11).  I wonder if previous versions on Android didn't automatically hide the keyboard? I haven't tried an emulator yet.  But would definitely be nice if the explanation addressed this if it is version-dependent!
