### ISSUE TITLE
Android Basics: xml-layouts

### ISSUE THREAD

**Issue by dsikar** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#72]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-xml-layouts#3

**In which task and step of the codelab can this issue be found?**

"At this point, your XML should look like this."

**Describe the problem**

Previously you had asked a:
```
android:padding="16dp"
```
to be added in the ConstraintLayout. It does not show in the completed code at this step.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@dsikar 
Thank you for reaching out to us. The code snippet is updated and will be published soon.
