### ISSUE TITLE
Android Basics: change-app-theme

### ISSUE THREAD

**Issue by seaboldt** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#74]
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-theme?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-change-app-theme#2

3-Themes

I'm on AndroidStudio 4.1.2.  The tutorial asks me to create a themes.xml file, but AndroidStudio has already created a filder with the same name containing 2 themes.xml files.  How di I continue?_

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
AndroidStudio 4.1.2
Samsung SM-S327VL

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@seaboldt 
Tha
Thank you for reaching out to us.
As the codelab mentions, you have to create theme files only if you are using versions of Android Studio prior to 4.1.

> In Android Studio 4.0 and earlier, styles and themes are located in the same resources file. You do not need to do the steps in this section if you are using Android 4.1 or later. 

Since you are using AndroidStudio 4.1.2, you can skip this step.
