### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by mtbossa** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#81]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#4

**In which task and step of the codelab can this issue be found?**
Modify classes in the hierarchy - Implement floorArea() for RoundHut

**Describe the problem**
At step 3 of **Implement floorArea() for RoundHut** step, the code is:
```kotlin
open class RoundHut(
   val residents: Int, 
   val radius: Double) : Dwelling(residents) {
   /* code */
}
```
What I think is wrong is that residents is being declared again. Residents is from Dwelling abstract class, the root class. Testing the code without declaring residents, like this, works the same way
```kotlin
open class RoundHut(
   residents: Int, 
   val radius: Double) : Dwelling(residents) {
   /* code */
}
```
**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@mtbossa 
Thank you so much for reporting this issue. This is fixed and will be published.
