### ISSUE TITLE
DAC navigation: Please don't break the back button

### ISSUE THREAD

**Issue by danielquinn** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#82]
### URL of codelab

[Link](https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#1)

### In which task and step of the codelab can this issue be found?

On every page of every codelab.

### Describe the problem

*Please* don't break the back button!  It's annoying at best and frustrating/alienating at worst.

### Steps to reproduce:

1. [Go to this page](https://developer.android.com/courses/pathways/android-basics-kotlin-unit-2-pathway-1)
2. Click `Classes and inheritance in Kotlin`.  The section will open downward.
3. Click `Take codelab`
4. This takes you to the first page in the exercise.  Scroll down and click `Next`
5. Click the back button on your browser.  This bounces you out of the entire exercise rather than taking you to the previous page in said exercise.
6. Now you're annoyed/disoriented, so you click the forward button in your browser.  Now you're on a search page with a bunch of featured articles and a search box.  Definitely not the codelab exercise you were working on.

### Environment

* Firefox 87.0b4 (64-bit)
* Arch Linux, GNOME 3.38.4 (X11)

**Comment by jtavva** [comment]
@danielquinn 
Please do not use the browser back button to navigate through the course!

**Comment by danielquinn** [comment]
Wait, are you serious?  You create a course *for a web browser* and don't support a standard browser function?  You're joking right?
