### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by ukjinlee** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#84]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#7

**In which task and step of the codelab can this issue be found?**
8. Summary

**Describe the problem**
"checkRadioButtonId" is wrong, and it should be "checkedRadioButtonId".

**Comment by jtavva** [comment]
@ukjinlee 
Thank you so much for reporting this issue. This is fixed and will be published.
