### ISSUE TITLE
Android Basics: xml-layouts

### ISSUE THREAD

**Issue by hase1998** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#85]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-xml-layouts#4

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

There is no line about describing padding of ConstraintLayout below 7th line.
Below code be inserted.
android:padding = "16dp"

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@hase1998 
We are adding the padding in the step, **Delete the TextView**. 
![image](https://user-images.githubusercontent.com/24260141/111370635-b7dd2e00-8655-11eb-895b-56788c6b9bf3.png)

Thank you for reaching out to us.
