### ISSUE TITLE
Android Basics: change-app-theme

### ISSUE THREAD

**Issue by AlexandrePlus** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#89]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-theme?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-change-app-theme#2

**In which task and step of the codelab can this issue be found?**
Change the app theme > 3 Themes > Learn about theme colors > 4 Look through the items in the file...

**Describe the problem**
        <item name="colorPrimaryDark">@color/purple_700</item>
instead of
        <item name="colorPrimaryVariant">@color/purple_700</item>

**Comment by jtavva** [comment]
@AlexandrePlus 
Thank you for reaching out to us.
Could you please add clear explanation of the problem?

**Comment by AlexandrePlus** [comment]
Hi!
Oops, the most important part has been taken out. Sorry about that.
So, it's witten `<item name="colorPrimaryDark">@color/purple_700</item>` instead of `<item name="colorPrimaryVariant">@color/purple_700</item>` (colorPrimary~~Dark~~**Variant**)

URL of codelab
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-theme#2

In which task and step of the codelab can this issue be found?
Change the app theme > 3 Themes > Learn about theme colors > 4 Look through the items in the file...
