### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by jkwatson** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#99]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#2

**In which task and step of the codelab can this issue be found?**
Step 3

**Describe the problem**
This codelab presents a harmful view of inheritance. Derived classes should *always* represent an "IS A" relationship with their parents. In this example, a "RoundTower" is represented as a child of "RoundHut" implying that a tower IS A hut, which is clearly not true. 

**Steps to reproduce?**
1. Go to the codelab
2. Click on step 3
3. See error... the example

![image](https://user-images.githubusercontent.com/858731/113440039-8330dc80-93a0-11eb-9794-618a472c4a0c.png)

**Comment by osuleymanova** [comment]
@jkwatson 
We appreciate your feedback. Thank you!
